// level: '600' | '730' | '860' | '990'
// category: 'verb' | 'noun' | 'adjective' | 'other'
const WORDS = [
  // ── 600点レベル ───────────────────────────────────────
  { word: "apply", meaning: "応募する、申請する", example: "apply for the position", level: "600", category: "verb" },
  { word: "attend", meaning: "出席する", example: "attend the meeting", level: "600", category: "verb" },
  { word: "cancel", meaning: "キャンセルする", example: "cancel the reservation", level: "600", category: "verb" },
  { word: "check", meaning: "確認する、調べる", example: "check the schedule", level: "600", category: "verb" },
  { word: "complete", meaning: "完了する", example: "complete the form", level: "600", category: "verb" },
  { word: "confirm", meaning: "確認する", example: "confirm the booking", level: "600", category: "verb" },
  { word: "contact", meaning: "連絡する", example: "contact the customer", level: "600", category: "verb" },
  { word: "deliver", meaning: "配達する", example: "deliver the package", level: "600", category: "verb" },
  { word: "discuss", meaning: "話し合う", example: "discuss the proposal", level: "600", category: "verb" },
  { word: "expand", meaning: "拡大する", example: "expand the business", level: "600", category: "verb" },
  { word: "hire", meaning: "雇う", example: "hire new employees", level: "600", category: "verb" },
  { word: "improve", meaning: "改善する", example: "improve customer service", level: "600", category: "verb" },
  { word: "increase", meaning: "増やす、増加する", example: "increase sales", level: "600", category: "verb" },
  { word: "inform", meaning: "知らせる", example: "inform the staff", level: "600", category: "verb" },
  { word: "launch", meaning: "発売する、立ち上げる", example: "launch a new product", level: "600", category: "verb" },
  { word: "manage", meaning: "管理する", example: "manage the project", level: "600", category: "verb" },
  { word: "meet", meaning: "会う、満たす", example: "meet the deadline", level: "600", category: "verb" },
  { word: "mention", meaning: "述べる", example: "mention in the email", level: "600", category: "verb" },
  { word: "notify", meaning: "通知する", example: "notify the team", level: "600", category: "verb" },
  { word: "open", meaning: "開く、開店する", example: "open a new branch", level: "600", category: "verb" },
  { word: "order", meaning: "注文する", example: "order office supplies", level: "600", category: "verb" },
  { word: "pay", meaning: "支払う", example: "pay the invoice", level: "600", category: "verb" },
  { word: "plan", meaning: "計画する", example: "plan the event", level: "600", category: "verb" },
  { word: "prepare", meaning: "準備する", example: "prepare for the presentation", level: "600", category: "verb" },
  { word: "provide", meaning: "提供する", example: "provide customer support", level: "600", category: "verb" },
  { word: "receive", meaning: "受け取る", example: "receive the shipment", level: "600", category: "verb" },
  { word: "recommend", meaning: "推薦する", example: "recommend a restaurant", level: "600", category: "verb" },
  { word: "reduce", meaning: "減らす", example: "reduce costs", level: "600", category: "verb" },
  { word: "report", meaning: "報告する", example: "report the results", level: "600", category: "verb" },
  { word: "request", meaning: "依頼する", example: "request a meeting", level: "600", category: "verb" },
  { word: "require", meaning: "必要とする", example: "require prior experience", level: "600", category: "verb" },
  { word: "review", meaning: "見直す", example: "review the contract", level: "600", category: "verb" },
  { word: "schedule", meaning: "予定を組む", example: "schedule an appointment", level: "600", category: "verb" },
  { word: "select", meaning: "選ぶ", example: "select the best candidate", level: "600", category: "verb" },
  { word: "send", meaning: "送る", example: "send a confirmation email", level: "600", category: "verb" },
  { word: "submit", meaning: "提出する", example: "submit the report", level: "600", category: "verb" },
  { word: "support", meaning: "支援する", example: "support the new initiative", level: "600", category: "verb" },
  { word: "update", meaning: "更新する", example: "update the database", level: "600", category: "verb" },
  { word: "use", meaning: "使用する", example: "use the new system", level: "600", category: "verb" },
  { word: "visit", meaning: "訪問する", example: "visit the client", level: "600", category: "verb" },
  { word: "work", meaning: "働く、機能する", example: "work on the project", level: "600", category: "verb" },
  { word: "write", meaning: "書く", example: "write a business report", level: "600", category: "verb" },
  { word: "agenda", meaning: "議題、議事録", example: "the meeting agenda", level: "600", category: "noun" },
  { word: "branch", meaning: "支店", example: "open a new branch", level: "600", category: "noun" },
  { word: "budget", meaning: "予算", example: "exceed the budget", level: "600", category: "noun" },
  { word: "candidate", meaning: "候補者", example: "a strong candidate", level: "600", category: "noun" },
  { word: "client", meaning: "顧客", example: "a corporate client", level: "600", category: "noun" },
  { word: "colleague", meaning: "同僚", example: "a trusted colleague", level: "600", category: "noun" },
  { word: "contract", meaning: "契約", example: "sign a contract", level: "600", category: "noun" },
  { word: "deadline", meaning: "締め切り", example: "meet the deadline", level: "600", category: "noun" },
  { word: "department", meaning: "部門", example: "the sales department", level: "600", category: "noun" },
  { word: "discount", meaning: "割引", example: "offer a discount", level: "600", category: "noun" },
  { word: "document", meaning: "書類", example: "sign the documents", level: "600", category: "noun" },
  { word: "email", meaning: "メール", example: "reply to an email", level: "600", category: "noun" },
  { word: "experience", meaning: "経験", example: "prior work experience", level: "600", category: "noun" },
  { word: "feedback", meaning: "フィードバック", example: "receive feedback", level: "600", category: "noun" },
  { word: "invoice", meaning: "請求書", example: "send an invoice", level: "600", category: "noun" },
  { word: "issue", meaning: "問題", example: "resolve the issue", level: "600", category: "noun" },
  { word: "location", meaning: "場所、立地", example: "a convenient location", level: "600", category: "noun" },
  { word: "market", meaning: "市場", example: "enter a new market", level: "600", category: "noun" },
  { word: "meeting", meaning: "会議", example: "attend a meeting", level: "600", category: "noun" },
  { word: "offer", meaning: "申し出、提案", example: "accept the job offer", level: "600", category: "noun" },
  { word: "opportunity", meaning: "機会", example: "a great opportunity", level: "600", category: "noun" },
  { word: "policy", meaning: "方針、規則", example: "company policy", level: "600", category: "noun" },
  { word: "position", meaning: "役職、立場", example: "apply for a position", level: "600", category: "noun" },
  { word: "priority", meaning: "優先事項", example: "top priority", level: "600", category: "noun" },
  { word: "profit", meaning: "利益", example: "increase profit", level: "600", category: "noun" },
  { word: "project", meaning: "プロジェクト", example: "lead a project", level: "600", category: "noun" },
  { word: "report", meaning: "報告書", example: "submit a report", level: "600", category: "noun" },
  { word: "request", meaning: "依頼、要請", example: "handle a request", level: "600", category: "noun" },
  { word: "research", meaning: "調査、研究", example: "conduct research", level: "600", category: "noun" },
  { word: "result", meaning: "結果", example: "achieve great results", level: "600", category: "noun" },
  { word: "safety", meaning: "安全", example: "workplace safety", level: "600", category: "noun" },
  { word: "salary", meaning: "給与", example: "a competitive salary", level: "600", category: "noun" },
  { word: "schedule", meaning: "スケジュール", example: "a busy schedule", level: "600", category: "noun" },
  { word: "shipment", meaning: "荷物、出荷", example: "track the shipment", level: "600", category: "noun" },
  { word: "staff", meaning: "スタッフ、職員", example: "train the staff", level: "600", category: "noun" },
  { word: "target", meaning: "目標", example: "exceed the target", level: "600", category: "noun" },
  { word: "team", meaning: "チーム", example: "a dedicated team", level: "600", category: "noun" },
  { word: "training", meaning: "研修、トレーニング", example: "attend a training session", level: "600", category: "noun" },
  { word: "available", meaning: "利用可能な、空いている", example: "available on request", level: "600", category: "adjective" },
  { word: "current", meaning: "現在の、最新の", example: "the current version", level: "600", category: "adjective" },
  { word: "effective", meaning: "効果的な", example: "an effective strategy", level: "600", category: "adjective" },
  { word: "free", meaning: "無料の、空いている", example: "free of charge", level: "600", category: "adjective" },
  { word: "full", meaning: "満員の、完全な", example: "full-time position", level: "600", category: "adjective" },
  { word: "local", meaning: "地元の、地域の", example: "a local supplier", level: "600", category: "adjective" },
  { word: "new", meaning: "新しい", example: "a new product line", level: "600", category: "adjective" },
  { word: "positive", meaning: "前向きな、良好な", example: "positive feedback", level: "600", category: "adjective" },
  { word: "recent", meaning: "最近の", example: "recent sales figures", level: "600", category: "adjective" },
  { word: "regarding", meaning: "〜に関して", example: "regarding your inquiry", level: "600", category: "other" },
  { word: "due", meaning: "期限の", example: "due by Friday", level: "600", category: "adjective" },

  // ── 730点レベル ───────────────────────────────────────
  { word: "accomplish", meaning: "達成する", example: "accomplish the goal", level: "730", category: "verb" },
  { word: "acquire", meaning: "取得する、買収する", example: "acquire a company", level: "730", category: "verb" },
  { word: "address", meaning: "対処する", example: "address the problem", level: "730", category: "verb" },
  { word: "adjust", meaning: "調整する", example: "adjust the price", level: "730", category: "verb" },
  { word: "advance", meaning: "昇進する、前進する", example: "advance to the next round", level: "730", category: "verb" },
  { word: "allocate", meaning: "割り当てる", example: "allocate the budget", level: "730", category: "verb" },
  { word: "analyze", meaning: "分析する", example: "analyze the data", level: "730", category: "verb" },
  { word: "announce", meaning: "発表する", example: "announce the results", level: "730", category: "verb" },
  { word: "approve", meaning: "承認する", example: "approve the proposal", level: "730", category: "verb" },
  { word: "assess", meaning: "評価する", example: "assess the risk", level: "730", category: "verb" },
  { word: "assign", meaning: "割り当てる", example: "assign tasks to staff", level: "730", category: "verb" },
  { word: "assist", meaning: "支援する", example: "assist with the project", level: "730", category: "verb" },
  { word: "authorize", meaning: "認可する", example: "authorize the payment", level: "730", category: "verb" },
  { word: "clarify", meaning: "明確にする", example: "clarify the requirements", level: "730", category: "verb" },
  { word: "collaborate", meaning: "協力する", example: "collaborate on the project", level: "730", category: "verb" },
  { word: "compensate", meaning: "補償する", example: "compensate for the delay", level: "730", category: "verb" },
  { word: "coordinate", meaning: "調整する", example: "coordinate the schedule", level: "730", category: "verb" },
  { word: "decline", meaning: "断る、低下する", example: "decline the offer", level: "730", category: "verb" },
  { word: "delegate", meaning: "委任する", example: "delegate responsibilities", level: "730", category: "verb" },
  { word: "demonstrate", meaning: "実演する", example: "demonstrate the product", level: "730", category: "verb" },
  { word: "determine", meaning: "決定する", example: "determine the cause", level: "730", category: "verb" },
  { word: "distribute", meaning: "配布する", example: "distribute the materials", level: "730", category: "verb" },
  { word: "eliminate", meaning: "排除する", example: "eliminate unnecessary costs", level: "730", category: "verb" },
  { word: "emphasize", meaning: "強調する", example: "emphasize the key points", level: "730", category: "verb" },
  { word: "enhance", meaning: "強化する", example: "enhance productivity", level: "730", category: "verb" },
  { word: "establish", meaning: "設立する", example: "establish a partnership", level: "730", category: "verb" },
  { word: "evaluate", meaning: "評価する", example: "evaluate performance", level: "730", category: "verb" },
  { word: "exceed", meaning: "超える", example: "exceed expectations", level: "730", category: "verb" },
  { word: "execute", meaning: "実行する", example: "execute the plan", level: "730", category: "verb" },
  { word: "focus", meaning: "集中する", example: "focus on customer needs", level: "730", category: "verb" },
  { word: "forecast", meaning: "予測する", example: "forecast sales growth", level: "730", category: "verb" },
  { word: "generate", meaning: "生み出す", example: "generate revenue", level: "730", category: "verb" },
  { word: "identify", meaning: "特定する", example: "identify the problem", level: "730", category: "verb" },
  { word: "implement", meaning: "実施する", example: "implement a new system", level: "730", category: "verb" },
  { word: "indicate", meaning: "示す", example: "indicate the next steps", level: "730", category: "verb" },
  { word: "invest", meaning: "投資する", example: "invest in technology", level: "730", category: "verb" },
  { word: "maintain", meaning: "維持する", example: "maintain quality standards", level: "730", category: "verb" },
  { word: "maximize", meaning: "最大化する", example: "maximize efficiency", level: "730", category: "verb" },
  { word: "measure", meaning: "測定する", example: "measure performance", level: "730", category: "verb" },
  { word: "negotiate", meaning: "交渉する", example: "negotiate the contract", level: "730", category: "verb" },
  { word: "obtain", meaning: "取得する", example: "obtain approval", level: "730", category: "verb" },
  { word: "organize", meaning: "組織する", example: "organize a conference", level: "730", category: "verb" },
  { word: "oversee", meaning: "監督する", example: "oversee the operations", level: "730", category: "verb" },
  { word: "participate", meaning: "参加する", example: "participate in the survey", level: "730", category: "verb" },
  { word: "perform", meaning: "実行する、業績を上げる", example: "perform well under pressure", level: "730", category: "verb" },
  { word: "promote", meaning: "昇進させる、促進する", example: "promote a product", level: "730", category: "verb" },
  { word: "propose", meaning: "提案する", example: "propose a solution", level: "730", category: "verb" },
  { word: "publish", meaning: "公開する", example: "publish a report", level: "730", category: "verb" },
  { word: "purchase", meaning: "購入する", example: "purchase new equipment", level: "730", category: "verb" },
  { word: "recognize", meaning: "認識する、表彰する", example: "recognize outstanding work", level: "730", category: "verb" },
  { word: "resolve", meaning: "解決する", example: "resolve a complaint", level: "730", category: "verb" },
  { word: "retain", meaning: "維持する、保持する", example: "retain top talent", level: "730", category: "verb" },
  { word: "transfer", meaning: "転送する、異動させる", example: "transfer to another office", level: "730", category: "verb" },
  { word: "utilize", meaning: "活用する", example: "utilize available resources", level: "730", category: "verb" },
  { word: "verify", meaning: "確認する", example: "verify the information", level: "730", category: "verb" },
  { word: "achievement", meaning: "達成、業績", example: "a major achievement", level: "730", category: "noun" },
  { word: "agreement", meaning: "合意、契約", example: "reach an agreement", level: "730", category: "noun" },
  { word: "application", meaning: "申請、応募書類", example: "submit an application", level: "730", category: "noun" },
  { word: "approval", meaning: "承認", example: "obtain approval", level: "730", category: "noun" },
  { word: "attachment", meaning: "添付ファイル", example: "see the attachment", level: "730", category: "noun" },
  { word: "attendance", meaning: "出席", example: "attendance is required", level: "730", category: "noun" },
  { word: "authority", meaning: "権限", example: "have the authority", level: "730", category: "noun" },
  { word: "certificate", meaning: "証明書", example: "a completion certificate", level: "730", category: "noun" },
  { word: "commitment", meaning: "コミットメント、約束", example: "show commitment", level: "730", category: "noun" },
  { word: "committee", meaning: "委員会", example: "the steering committee", level: "730", category: "noun" },
  { word: "compensation", meaning: "報酬、補償", example: "a competitive compensation", level: "730", category: "noun" },
  { word: "conference", meaning: "会議、会合", example: "an annual conference", level: "730", category: "noun" },
  { word: "conflict", meaning: "衝突、対立", example: "a scheduling conflict", level: "730", category: "noun" },
  { word: "contribution", meaning: "貢献", example: "make a contribution", level: "730", category: "noun" },
  { word: "deadline", meaning: "締め切り", example: "extend the deadline", level: "730", category: "noun" },
  { word: "decision", meaning: "決定", example: "make a final decision", level: "730", category: "noun" },
  { word: "demand", meaning: "需要", example: "growing demand", level: "730", category: "noun" },
  { word: "description", meaning: "説明、記述", example: "a job description", level: "730", category: "noun" },
  { word: "division", meaning: "部門、事業部", example: "the marketing division", level: "730", category: "noun" },
  { word: "efficiency", meaning: "効率", example: "improve efficiency", level: "730", category: "noun" },
  { word: "expansion", meaning: "拡大", example: "business expansion", level: "730", category: "noun" },
  { word: "extension", meaning: "延長、内線", example: "an extension of the deadline", level: "730", category: "noun" },
  { word: "forecast", meaning: "予測、見通し", example: "the sales forecast", level: "730", category: "noun" },
  { word: "fund", meaning: "資金", example: "secure additional funds", level: "730", category: "noun" },
  { word: "goal", meaning: "目標", example: "set a goal", level: "730", category: "noun" },
  { word: "growth", meaning: "成長", example: "drive growth", level: "730", category: "noun" },
  { word: "guideline", meaning: "ガイドライン", example: "follow the guidelines", level: "730", category: "noun" },
  { word: "impact", meaning: "影響", example: "a positive impact", level: "730", category: "noun" },
  { word: "income", meaning: "収入", example: "annual income", level: "730", category: "noun" },
  { word: "initiative", meaning: "取り組み、主導権", example: "a cost-saving initiative", level: "730", category: "noun" },
  { word: "inventory", meaning: "在庫", example: "manage inventory", level: "730", category: "noun" },
  { word: "investment", meaning: "投資", example: "return on investment", level: "730", category: "noun" },
  { word: "leadership", meaning: "リーダーシップ", example: "strong leadership", level: "730", category: "noun" },
  { word: "margin", meaning: "利益率、余白", example: "a profit margin", level: "730", category: "noun" },
  { word: "material", meaning: "資料、素材", example: "training materials", level: "730", category: "noun" },
  { word: "motivation", meaning: "モチベーション", example: "boost motivation", level: "730", category: "noun" },
  { word: "network", meaning: "ネットワーク、人脈", example: "build a network", level: "730", category: "noun" },
  { word: "objective", meaning: "目標、目的", example: "meet the objectives", level: "730", category: "noun" },
  { word: "output", meaning: "産出量、成果", example: "increase output", level: "730", category: "noun" },
  { word: "performance", meaning: "業績、パフォーマンス", example: "evaluate performance", level: "730", category: "noun" },
  { word: "procedure", meaning: "手順", example: "follow the procedure", level: "730", category: "noun" },
  { word: "qualification", meaning: "資格", example: "the required qualifications", level: "730", category: "noun" },
  { word: "quarter", meaning: "四半期", example: "in the third quarter", level: "730", category: "noun" },
  { word: "regulation", meaning: "規制、規則", example: "comply with regulations", level: "730", category: "noun" },
  { word: "reputation", meaning: "評判", example: "a strong reputation", level: "730", category: "noun" },
  { word: "resource", meaning: "資源、リソース", example: "allocate resources", level: "730", category: "noun" },
  { word: "revenue", meaning: "収益、売上", example: "increase revenue", level: "730", category: "noun" },
  { word: "sector", meaning: "部門、分野", example: "the financial sector", level: "730", category: "noun" },
  { word: "solution", meaning: "解決策", example: "find a solution", level: "730", category: "noun" },
  { word: "statement", meaning: "声明、明細書", example: "a financial statement", level: "730", category: "noun" },
  { word: "strategy", meaning: "戦略", example: "develop a strategy", level: "730", category: "noun" },
  { word: "supplier", meaning: "サプライヤー", example: "a reliable supplier", level: "730", category: "noun" },
  { word: "survey", meaning: "調査、アンケート", example: "conduct a survey", level: "730", category: "noun" },
  { word: "timeline", meaning: "タイムライン、期日", example: "set a timeline", level: "730", category: "noun" },
  { word: "transaction", meaning: "取引", example: "complete a transaction", level: "730", category: "noun" },
  { word: "trend", meaning: "傾向、トレンド", example: "a growing trend", level: "730", category: "noun" },
  { word: "vendor", meaning: "販売業者、ベンダー", example: "select a vendor", level: "730", category: "noun" },
  { word: "workforce", meaning: "労働力、従業員", example: "a skilled workforce", level: "730", category: "noun" },
  { word: "adequate", meaning: "十分な", example: "adequate preparation", level: "730", category: "adjective" },
  { word: "annual", meaning: "毎年の、年次の", example: "the annual report", level: "730", category: "adjective" },
  { word: "competitive", meaning: "競争力のある", example: "a competitive price", level: "730", category: "adjective" },
  { word: "confidential", meaning: "機密の", example: "confidential information", level: "730", category: "adjective" },
  { word: "convenient", meaning: "便利な", example: "a convenient location", level: "730", category: "adjective" },
  { word: "efficient", meaning: "効率的な", example: "an efficient process", level: "730", category: "adjective" },
  { word: "eligible", meaning: "資格がある", example: "eligible for promotion", level: "730", category: "adjective" },
  { word: "essential", meaning: "必須の", example: "essential skills", level: "730", category: "adjective" },
  { word: "flexible", meaning: "柔軟な", example: "a flexible schedule", level: "730", category: "adjective" },
  { word: "mandatory", meaning: "義務的な", example: "mandatory training", level: "730", category: "adjective" },
  { word: "productive", meaning: "生産的な", example: "a productive meeting", level: "730", category: "adjective" },
  { word: "reliable", meaning: "信頼できる", example: "a reliable partner", level: "730", category: "adjective" },
  { word: "responsible", meaning: "責任がある", example: "responsible for the project", level: "730", category: "adjective" },
  { word: "significant", meaning: "重要な、著しい", example: "a significant improvement", level: "730", category: "adjective" },
  { word: "suitable", meaning: "適切な", example: "suitable for the role", level: "730", category: "adjective" },
  { word: "temporary", meaning: "一時的な", example: "a temporary position", level: "730", category: "adjective" },
  { word: "despite", meaning: "〜にもかかわらず", example: "despite the challenges", level: "730", category: "other" },
  { word: "throughout", meaning: "〜を通じて", example: "throughout the year", level: "730", category: "other" },
  { word: "unless", meaning: "〜でない限り", example: "unless otherwise stated", level: "730", category: "other" },

  // ── 860点レベル ───────────────────────────────────────
  { word: "accommodate", meaning: "収容する、対応する", example: "accommodate all requests", level: "860", category: "verb" },
  { word: "accelerate", meaning: "加速する", example: "accelerate the process", level: "860", category: "verb" },
  { word: "anticipate", meaning: "予期する", example: "anticipate future demand", level: "860", category: "verb" },
  { word: "attribute", meaning: "〜のせいにする、〜に帰する", example: "attribute success to teamwork", level: "860", category: "verb" },
  { word: "comply", meaning: "従う", example: "comply with regulations", level: "860", category: "verb" },
  { word: "consolidate", meaning: "統合する", example: "consolidate the departments", level: "860", category: "verb" },
  { word: "convene", meaning: "召集する", example: "convene a meeting", level: "860", category: "verb" },
  { word: "defer", meaning: "延期する", example: "defer the decision", level: "860", category: "verb" },
  { word: "depreciate", meaning: "減価償却する", example: "depreciate over five years", level: "860", category: "verb" },
  { word: "designate", meaning: "指定する", example: "designate a parking space", level: "860", category: "verb" },
  { word: "differentiate", meaning: "差別化する", example: "differentiate from competitors", level: "860", category: "verb" },
  { word: "disclose", meaning: "開示する", example: "disclose financial information", level: "860", category: "verb" },
  { word: "dispatch", meaning: "派遣する、発送する", example: "dispatch a technician", level: "860", category: "verb" },
  { word: "diversify", meaning: "多様化する", example: "diversify the portfolio", level: "860", category: "verb" },
  { word: "expedite", meaning: "迅速に処理する", example: "expedite the order", level: "860", category: "verb" },
  { word: "facilitate", meaning: "促進する", example: "facilitate the discussion", level: "860", category: "verb" },
  { word: "fluctuate", meaning: "変動する", example: "prices fluctuate daily", level: "860", category: "verb" },
  { word: "incur", meaning: "（費用などを）被る", example: "incur additional costs", level: "860", category: "verb" },
  { word: "initiate", meaning: "開始する", example: "initiate a new project", level: "860", category: "verb" },
  { word: "innovate", meaning: "革新する", example: "innovate constantly", level: "860", category: "verb" },
  { word: "integrate", meaning: "統合する", example: "integrate the two systems", level: "860", category: "verb" },
  { word: "leverage", meaning: "活用する", example: "leverage existing resources", level: "860", category: "verb" },
  { word: "mitigate", meaning: "軽減する", example: "mitigate the risk", level: "860", category: "verb" },
  { word: "monitor", meaning: "監視する", example: "monitor the progress", level: "860", category: "verb" },
  { word: "negotiate", meaning: "交渉する", example: "negotiate favorable terms", level: "860", category: "verb" },
  { word: "notify", meaning: "通知する", example: "notify in advance", level: "860", category: "verb" },
  { word: "optimize", meaning: "最適化する", example: "optimize the workflow", level: "860", category: "verb" },
  { word: "outsource", meaning: "外注する", example: "outsource the work", level: "860", category: "verb" },
  { word: "oversee", meaning: "監督する", example: "oversee the entire operation", level: "860", category: "verb" },
  { word: "prioritize", meaning: "優先する", example: "prioritize urgent tasks", level: "860", category: "verb" },
  { word: "reimburse", meaning: "払い戻す", example: "reimburse travel expenses", level: "860", category: "verb" },
  { word: "restructure", meaning: "再編する", example: "restructure the organization", level: "860", category: "verb" },
  { word: "streamline", meaning: "合理化する", example: "streamline the process", level: "860", category: "verb" },
  { word: "sustain", meaning: "維持する", example: "sustain growth", level: "860", category: "verb" },
  { word: "terminate", meaning: "終了する、解雇する", example: "terminate the contract", level: "860", category: "verb" },
  { word: "waive", meaning: "放棄する", example: "waive the fee", level: "860", category: "verb" },
  { word: "acquisition", meaning: "買収、取得", example: "a major acquisition", level: "860", category: "noun" },
  { word: "amendment", meaning: "修正、改正", example: "propose an amendment", level: "860", category: "noun" },
  { word: "audit", meaning: "監査", example: "conduct an audit", level: "860", category: "noun" },
  { word: "benchmark", meaning: "基準、目安", example: "set a benchmark", level: "860", category: "noun" },
  { word: "clause", meaning: "条項", example: "a contract clause", level: "860", category: "noun" },
  { word: "compliance", meaning: "コンプライアンス、遵守", example: "ensure compliance", level: "860", category: "noun" },
  { word: "consequence", meaning: "結果、影響", example: "serious consequences", level: "860", category: "noun" },
  { word: "constraint", meaning: "制約", example: "budget constraints", level: "860", category: "noun" },
  { word: "contingency", meaning: "不測の事態", example: "a contingency plan", level: "860", category: "noun" },
  { word: "criterion", meaning: "基準", example: "the selection criterion", level: "860", category: "noun" },
  { word: "deficit", meaning: "赤字、不足", example: "a budget deficit", level: "860", category: "noun" },
  { word: "delegation", meaning: "委任、代表団", example: "a trade delegation", level: "860", category: "noun" },
  { word: "disruption", meaning: "混乱、中断", example: "minimize disruption", level: "860", category: "noun" },
  { word: "fluctuation", meaning: "変動", example: "price fluctuations", level: "860", category: "noun" },
  { word: "framework", meaning: "枠組み", example: "a legal framework", level: "860", category: "noun" },
  { word: "incentive", meaning: "インセンティブ、動機", example: "offer an incentive", level: "860", category: "noun" },
  { word: "infrastructure", meaning: "インフラ", example: "upgrade the infrastructure", level: "860", category: "noun" },
  { word: "leverage", meaning: "てこ、影響力", example: "use as leverage", level: "860", category: "noun" },
  { word: "liability", meaning: "負債、法的責任", example: "limit liability", level: "860", category: "noun" },
  { word: "logistics", meaning: "物流", example: "manage logistics", level: "860", category: "noun" },
  { word: "merger", meaning: "合併", example: "a corporate merger", level: "860", category: "noun" },
  { word: "milestone", meaning: "節目、重要な段階", example: "reach a milestone", level: "860", category: "noun" },
  { word: "overhead", meaning: "経費、諸経費", example: "reduce overhead costs", level: "860", category: "noun" },
  { word: "portfolio", meaning: "ポートフォリオ", example: "a diversified portfolio", level: "860", category: "noun" },
  { word: "procurement", meaning: "調達", example: "streamline procurement", level: "860", category: "noun" },
  { word: "prospect", meaning: "見込み客、見通し", example: "a promising prospect", level: "860", category: "noun" },
  { word: "prototype", meaning: "試作品", example: "develop a prototype", level: "860", category: "noun" },
  { word: "provision", meaning: "規定、条項", example: "make provisions for", level: "860", category: "noun" },
  { word: "reimbursement", meaning: "払い戻し", example: "expense reimbursement", level: "860", category: "noun" },
  { word: "retention", meaning: "保持、定着率", example: "improve staff retention", level: "860", category: "noun" },
  { word: "revenue", meaning: "収益", example: "boost revenue streams", level: "860", category: "noun" },
  { word: "subsidiary", meaning: "子会社", example: "a wholly-owned subsidiary", level: "860", category: "noun" },
  { word: "turnover", meaning: "売上高、離職率", example: "reduce staff turnover", level: "860", category: "noun" },
  { word: "valuation", meaning: "評価額", example: "a company valuation", level: "860", category: "noun" },
  { word: "viable", meaning: "実行可能な", example: "a viable option", level: "860", category: "adjective" },
  { word: "comprehensive", meaning: "包括的な", example: "a comprehensive plan", level: "860", category: "adjective" },
  { word: "consecutive", meaning: "連続した", example: "three consecutive quarters", level: "860", category: "adjective" },
  { word: "detrimental", meaning: "有害な、不利な", example: "detrimental to health", level: "860", category: "adjective" },
  { word: "domestic", meaning: "国内の", example: "domestic and international", level: "860", category: "adjective" },
  { word: "eligible", meaning: "資格がある", example: "eligible for benefits", level: "860", category: "adjective" },
  { word: "exclusive", meaning: "独占的な、限定的な", example: "an exclusive contract", level: "860", category: "adjective" },
  { word: "imminent", meaning: "差し迫った", example: "an imminent deadline", level: "860", category: "adjective" },
  { word: "preliminary", meaning: "予備的な", example: "preliminary results", level: "860", category: "adjective" },
  { word: "stringent", meaning: "厳しい", example: "stringent requirements", level: "860", category: "adjective" },
  { word: "substantial", meaning: "かなりの", example: "a substantial increase", level: "860", category: "adjective" },
  { word: "sustainable", meaning: "持続可能な", example: "sustainable growth", level: "860", category: "adjective" },
  { word: "transparent", meaning: "透明な", example: "transparent pricing", level: "860", category: "adjective" },
  { word: "consecutive", meaning: "連続した", example: "consecutive wins", level: "860", category: "adjective" },
  { word: "pursuant", meaning: "〜に従って", example: "pursuant to the agreement", level: "860", category: "other" },
  { word: "hereby", meaning: "これにより", example: "hereby notify you", level: "860", category: "other" },
  { word: "notwithstanding", meaning: "〜にもかかわらず", example: "notwithstanding the delay", level: "860", category: "other" },

  // ── 990点レベル ───────────────────────────────────────
  { word: "arbitrate", meaning: "仲裁する", example: "arbitrate the dispute", level: "990", category: "verb" },
  { word: "ascertain", meaning: "確認する、突き止める", example: "ascertain the facts", level: "990", category: "verb" },
  { word: "circumvent", meaning: "回避する", example: "circumvent the rules", level: "990", category: "verb" },
  { word: "codify", meaning: "成文化する", example: "codify the regulations", level: "990", category: "verb" },
  { word: "corroborate", meaning: "裏付ける", example: "corroborate the findings", level: "990", category: "verb" },
  { word: "delineate", meaning: "明確に述べる", example: "delineate responsibilities", level: "990", category: "verb" },
  { word: "disseminate", meaning: "普及させる", example: "disseminate the information", level: "990", category: "verb" },
  { word: "divulge", meaning: "漏らす、開示する", example: "divulge confidential data", level: "990", category: "verb" },
  { word: "effectuate", meaning: "実現する", example: "effectuate the plan", level: "990", category: "verb" },
  { word: "engender", meaning: "生み出す", example: "engender trust", level: "990", category: "verb" },
  { word: "enumerate", meaning: "列挙する", example: "enumerate the conditions", level: "990", category: "verb" },
  { word: "exacerbate", meaning: "悪化させる", example: "exacerbate the situation", level: "990", category: "verb" },
  { word: "forestall", meaning: "先手を打つ", example: "forestall potential problems", level: "990", category: "verb" },
  { word: "galvanize", meaning: "活性化させる", example: "galvanize the team", level: "990", category: "verb" },
  { word: "impede", meaning: "妨げる", example: "impede progress", level: "990", category: "verb" },
  { word: "inaugurate", meaning: "就任させる、開始する", example: "inaugurate a new policy", level: "990", category: "verb" },
  { word: "indemnify", meaning: "補償する", example: "indemnify against losses", level: "990", category: "verb" },
  { word: "mandate", meaning: "命じる", example: "mandate compliance", level: "990", category: "verb" },
  { word: "obviate", meaning: "取り除く", example: "obviate the need for", level: "990", category: "verb" },
  { word: "perpetuate", meaning: "永続させる", example: "perpetuate the practice", level: "990", category: "verb" },
  { word: "preclude", meaning: "除外する、妨げる", example: "preclude further action", level: "990", category: "verb" },
  { word: "promulgate", meaning: "公布する", example: "promulgate new rules", level: "990", category: "verb" },
  { word: "ratify", meaning: "批准する", example: "ratify the treaty", level: "990", category: "verb" },
  { word: "reconcile", meaning: "和解させる、照合する", example: "reconcile the accounts", level: "990", category: "verb" },
  { word: "rectify", meaning: "修正する", example: "rectify the error", level: "990", category: "verb" },
  { word: "remunerate", meaning: "報酬を払う", example: "remunerate fairly", level: "990", category: "verb" },
  { word: "rescind", meaning: "廃止する", example: "rescind the decision", level: "990", category: "verb" },
  { word: "stipulate", meaning: "規定する", example: "stipulate the terms", level: "990", category: "verb" },
  { word: "supersede", meaning: "取って代わる", example: "supersede the old policy", level: "990", category: "verb" },
  { word: "adjudicate", meaning: "判定する", example: "adjudicate the claim", level: "990", category: "verb" },
  { word: "accrual", meaning: "累積、発生", example: "accrual basis accounting", level: "990", category: "noun" },
  { word: "arbitration", meaning: "仲裁", example: "settle through arbitration", level: "990", category: "noun" },
  { word: "caveat", meaning: "警告、条件", example: "with one caveat", level: "990", category: "noun" },
  { word: "collateral", meaning: "担保", example: "provide collateral", level: "990", category: "noun" },
  { word: "compendium", meaning: "概要、要約書", example: "a compendium of regulations", level: "990", category: "noun" },
  { word: "consortium", meaning: "コンソーシアム、共同体", example: "form a consortium", level: "990", category: "noun" },
  { word: "debenture", meaning: "社債", example: "issue a debenture", level: "990", category: "noun" },
  { word: "encumbrance", meaning: "障害、負債", example: "free from encumbrance", level: "990", category: "noun" },
  { word: "fiduciary", meaning: "受託者、信任の", example: "fiduciary responsibility", level: "990", category: "noun" },
  { word: "indemnity", meaning: "損害補償", example: "an indemnity clause", level: "990", category: "noun" },
  { word: "injunction", meaning: "差し止め命令", example: "seek an injunction", level: "990", category: "noun" },
  { word: "insolvency", meaning: "支払い不能", example: "file for insolvency", level: "990", category: "noun" },
  { word: "jurisprudence", meaning: "法学、判例", example: "corporate jurisprudence", level: "990", category: "noun" },
  { word: "liquidation", meaning: "清算", example: "enter liquidation", level: "990", category: "noun" },
  { word: "moratorium", meaning: "一時停止、猶予期間", example: "a debt moratorium", level: "990", category: "noun" },
  { word: "nexus", meaning: "関連、つながり", example: "a nexus of relationships", level: "990", category: "noun" },
  { word: "pecuniary", meaning: "金銭上の", example: "pecuniary gain", level: "990", category: "noun" },
  { word: "prerogative", meaning: "特権", example: "management's prerogative", level: "990", category: "noun" },
  { word: "proviso", meaning: "条件、但し書き", example: "with the proviso that", level: "990", category: "noun" },
  { word: "recourse", meaning: "手段、頼りにすること", example: "have recourse to arbitration", level: "990", category: "noun" },
  { word: "sequester", meaning: "差し押さえる", example: "sequester assets", level: "990", category: "verb" },
  { word: "solvency", meaning: "支払い能力", example: "maintain solvency", level: "990", category: "noun" },
  { word: "subrogation", meaning: "代位（法律用語）", example: "rights of subrogation", level: "990", category: "noun" },
  { word: "encumbrance", meaning: "担保権、障害", example: "clear the encumbrance", level: "990", category: "noun" },
  { word: "amortization", meaning: "償却", example: "amortization schedule", level: "990", category: "noun" },
  { word: "perfunctory", meaning: "形式的な", example: "a perfunctory review", level: "990", category: "adjective" },
  { word: "insolvent", meaning: "支払い不能の", example: "declared insolvent", level: "990", category: "adjective" },
  { word: "commensurate", meaning: "相応の", example: "commensurate with experience", level: "990", category: "adjective" },
  { word: "exigent", meaning: "緊急の", example: "exigent circumstances", level: "990", category: "adjective" },
  { word: "germane", meaning: "関連する、適切な", example: "germane to the discussion", level: "990", category: "adjective" },
  { word: "inimical", meaning: "有害な、敵対的な", example: "inimical to growth", level: "990", category: "adjective" },
  { word: "onerous", meaning: "厄介な、負担の多い", example: "onerous regulations", level: "990", category: "adjective" },
  { word: "perspicacious", meaning: "洞察力のある", example: "a perspicacious analysis", level: "990", category: "adjective" },
  { word: "proscribed", meaning: "禁止された", example: "proscribed activities", level: "990", category: "adjective" },
  { word: "solvent", meaning: "支払い能力のある", example: "remain solvent", level: "990", category: "adjective" },
];
