// level: '600' | '730' | '860' | '990'
// category: 'verb' | 'noun' | 'adjective' | 'other'
const WORDS = [
  // ── 600点レベル ───────────────────────────────────────
  { word: "apply", meaning: "応募する、申請する", example: "apply for the position", exampleJa: "その役職に応募する", level: "600", category: "verb" },
  { word: "attend", meaning: "出席する", example: "attend the meeting", exampleJa: "会議に出席する", level: "600", category: "verb" },
  { word: "cancel", meaning: "キャンセルする", example: "cancel the reservation", exampleJa: "予約をキャンセルする", level: "600", category: "verb" },
  { word: "check", meaning: "確認する、調べる", example: "check the schedule", exampleJa: "スケジュールを確認する", level: "600", category: "verb" },
  { word: "complete", meaning: "完了する", example: "complete the form", exampleJa: "フォームに記入する", level: "600", category: "verb" },
  { word: "confirm", meaning: "確認する", example: "confirm the booking", exampleJa: "予約を確認する", level: "600", category: "verb" },
  { word: "contact", meaning: "連絡する", example: "contact the customer", exampleJa: "顧客に連絡する", level: "600", category: "verb" },
  { word: "deliver", meaning: "配達する", example: "deliver the package", exampleJa: "荷物を配達する", level: "600", category: "verb" },
  { word: "discuss", meaning: "話し合う", example: "discuss the proposal", exampleJa: "提案について話し合う", level: "600", category: "verb" },
  { word: "expand", meaning: "拡大する", example: "expand the business", exampleJa: "事業を拡大する", level: "600", category: "verb" },
  { word: "hire", meaning: "雇う", example: "hire new employees", exampleJa: "新しい従業員を雇う", level: "600", category: "verb" },
  { word: "improve", meaning: "改善する", example: "improve customer service", exampleJa: "顧客サービスを改善する", level: "600", category: "verb" },
  { word: "increase", meaning: "増やす、増加する", example: "increase sales", exampleJa: "売上を伸ばす", level: "600", category: "verb" },
  { word: "inform", meaning: "知らせる", example: "inform the staff", exampleJa: "スタッフに知らせる", level: "600", category: "verb" },
  { word: "launch", meaning: "発売する、立ち上げる", example: "launch a new product", exampleJa: "新製品を発売する", level: "600", category: "verb" },
  { word: "manage", meaning: "管理する", example: "manage the project", exampleJa: "プロジェクトを管理する", level: "600", category: "verb" },
  { word: "meet", meaning: "会う、満たす", example: "meet the deadline", exampleJa: "締め切りを守る", level: "600", category: "verb" },
  { word: "mention", meaning: "述べる", example: "mention in the email", exampleJa: "メールで述べる", level: "600", category: "verb" },
  { word: "notify", meaning: "通知する", example: "notify the team", exampleJa: "チームに通知する", level: "600", category: "verb" },
  { word: "open", meaning: "開く、開店する", example: "open a new branch", exampleJa: "新しい支店を開く", level: "600", category: "verb" },
  { word: "order", meaning: "注文する", example: "order office supplies", exampleJa: "事務用品を注文する", level: "600", category: "verb" },
  { word: "pay", meaning: "支払う", example: "pay the invoice", exampleJa: "請求書を支払う", level: "600", category: "verb" },
  { word: "plan", meaning: "計画する", example: "plan the event", exampleJa: "イベントを計画する", level: "600", category: "verb" },
  { word: "prepare", meaning: "準備する", example: "prepare for the presentation", exampleJa: "プレゼンの準備をする", level: "600", category: "verb" },
  { word: "provide", meaning: "提供する", example: "provide customer support", exampleJa: "顧客サポートを提供する", level: "600", category: "verb" },
  { word: "receive", meaning: "受け取る", example: "receive the shipment", exampleJa: "荷物を受け取る", level: "600", category: "verb" },
  { word: "recommend", meaning: "推薦する", example: "recommend a restaurant", exampleJa: "レストランを勧める", level: "600", category: "verb" },
  { word: "reduce", meaning: "減らす", example: "reduce costs", exampleJa: "コストを削減する", level: "600", category: "verb" },
  { word: "report", meaning: "報告する", example: "report the results", exampleJa: "結果を報告する", level: "600", category: "verb" },
  { word: "request", meaning: "依頼する", example: "request a meeting", exampleJa: "会議を依頼する", level: "600", category: "verb" },
  { word: "require", meaning: "必要とする", example: "require prior experience", exampleJa: "経験を必要とする", level: "600", category: "verb" },
  { word: "review", meaning: "見直す", example: "review the contract", exampleJa: "契約書を見直す", level: "600", category: "verb" },
  { word: "schedule", meaning: "予定を組む", example: "schedule an appointment", exampleJa: "予約を入れる", level: "600", category: "verb" },
  { word: "select", meaning: "選ぶ", example: "select the best candidate", exampleJa: "最適な候補者を選ぶ", level: "600", category: "verb" },
  { word: "send", meaning: "送る", example: "send a confirmation email", exampleJa: "確認メールを送る", level: "600", category: "verb" },
  { word: "submit", meaning: "提出する", example: "submit the report", exampleJa: "報告書を提出する", level: "600", category: "verb" },
  { word: "support", meaning: "支援する", example: "support the new initiative", exampleJa: "新しい取り組みを支援する", level: "600", category: "verb" },
  { word: "update", meaning: "更新する", example: "update the database", exampleJa: "データベースを更新する", level: "600", category: "verb" },
  { word: "use", meaning: "使用する", example: "use the new system", exampleJa: "新しいシステムを使用する", level: "600", category: "verb" },
  { word: "visit", meaning: "訪問する", example: "visit the client", exampleJa: "顧客を訪問する", level: "600", category: "verb" },
  { word: "work", meaning: "働く、機能する", example: "work on the project", exampleJa: "プロジェクトに取り組む", level: "600", category: "verb" },
  { word: "write", meaning: "書く", example: "write a business report", exampleJa: "業務報告書を書く", level: "600", category: "verb" },
  { word: "agenda", meaning: "議題、議事録", example: "the meeting agenda", exampleJa: "会議の議題", level: "600", category: "noun" },
  { word: "branch", meaning: "支店", example: "open a new branch", exampleJa: "新しい支店を開く", level: "600", category: "noun" },
  { word: "budget", meaning: "予算", example: "exceed the budget", exampleJa: "予算を超える", level: "600", category: "noun" },
  { word: "candidate", meaning: "候補者", example: "a strong candidate", exampleJa: "有力な候補者", level: "600", category: "noun" },
  { word: "client", meaning: "顧客", example: "a corporate client", exampleJa: "法人顧客", level: "600", category: "noun" },
  { word: "colleague", meaning: "同僚", example: "a trusted colleague", exampleJa: "信頼できる同僚", level: "600", category: "noun" },
  { word: "contract", meaning: "契約", example: "sign a contract", exampleJa: "契約書に署名する", level: "600", category: "noun" },
  { word: "deadline", meaning: "締め切り", example: "meet the deadline", exampleJa: "締め切りを守る", level: "600", category: "noun" },
  { word: "department", meaning: "部門", example: "the sales department", exampleJa: "営業部門", level: "600", category: "noun" },
  { word: "discount", meaning: "割引", example: "offer a discount", exampleJa: "割引を提供する", level: "600", category: "noun" },
  { word: "document", meaning: "書類", example: "sign the documents", exampleJa: "書類に署名する", level: "600", category: "noun" },
  { word: "email", meaning: "メール", example: "reply to an email", exampleJa: "メールに返信する", level: "600", category: "noun" },
  { word: "experience", meaning: "経験", example: "prior work experience", exampleJa: "実務経験", level: "600", category: "noun" },
  { word: "feedback", meaning: "フィードバック", example: "receive feedback", exampleJa: "フィードバックをもらう", level: "600", category: "noun" },
  { word: "invoice", meaning: "請求書", example: "send an invoice", exampleJa: "請求書を送る", level: "600", category: "noun" },
  { word: "issue", meaning: "問題", example: "resolve the issue", exampleJa: "問題を解決する", level: "600", category: "noun" },
  { word: "location", meaning: "場所、立地", example: "a convenient location", exampleJa: "便利な立地", level: "600", category: "noun" },
  { word: "market", meaning: "市場", example: "enter a new market", exampleJa: "新しい市場に参入する", level: "600", category: "noun" },
  { word: "meeting", meaning: "会議", example: "attend a meeting", exampleJa: "会議に出席する", level: "600", category: "noun" },
  { word: "offer", meaning: "申し出、提案", example: "accept the job offer", exampleJa: "内定を承諾する", level: "600", category: "noun" },
  { word: "opportunity", meaning: "機会", example: "a great opportunity", exampleJa: "絶好のチャンス", level: "600", category: "noun" },
  { word: "policy", meaning: "方針、規則", example: "company policy", exampleJa: "会社の方針", level: "600", category: "noun" },
  { word: "position", meaning: "役職、立場", example: "apply for a position", exampleJa: "ポジションに応募する", level: "600", category: "noun" },
  { word: "priority", meaning: "優先事項", example: "top priority", exampleJa: "最優先事項", level: "600", category: "noun" },
  { word: "profit", meaning: "利益", example: "increase profit", exampleJa: "利益を増やす", level: "600", category: "noun" },
  { word: "project", meaning: "プロジェクト", example: "lead a project", exampleJa: "プロジェクトを率いる", level: "600", category: "noun" },
  { word: "report", meaning: "報告書", example: "submit a report", exampleJa: "報告書を提出する", level: "600", category: "noun" },
  { word: "request", meaning: "依頼、要請", example: "handle a request", exampleJa: "依頼に対応する", level: "600", category: "noun" },
  { word: "research", meaning: "調査、研究", example: "conduct research", exampleJa: "調査を行う", level: "600", category: "noun" },
  { word: "result", meaning: "結果", example: "achieve great results", exampleJa: "優れた結果を出す", level: "600", category: "noun" },
  { word: "safety", meaning: "安全", example: "workplace safety", exampleJa: "職場の安全", level: "600", category: "noun" },
  { word: "salary", meaning: "給与", example: "a competitive salary", exampleJa: "競争力のある給与", level: "600", category: "noun" },
  { word: "schedule", meaning: "スケジュール", example: "a busy schedule", exampleJa: "過密なスケジュール", level: "600", category: "noun" },
  { word: "shipment", meaning: "荷物、出荷", example: "track the shipment", exampleJa: "荷物を追跡する", level: "600", category: "noun" },
  { word: "staff", meaning: "スタッフ、職員", example: "train the staff", exampleJa: "スタッフを研修する", level: "600", category: "noun" },
  { word: "target", meaning: "目標", example: "exceed the target", exampleJa: "目標を超える", level: "600", category: "noun" },
  { word: "team", meaning: "チーム", example: "a dedicated team", exampleJa: "献身的なチーム", level: "600", category: "noun" },
  { word: "training", meaning: "研修、トレーニング", example: "attend a training session", exampleJa: "研修に参加する", level: "600", category: "noun" },
  { word: "available", meaning: "利用可能な、空いている", example: "available on request", exampleJa: "依頼があれば利用可能", level: "600", category: "adjective" },
  { word: "current", meaning: "現在の、最新の", example: "the current version", exampleJa: "現在のバージョン", level: "600", category: "adjective" },
  { word: "effective", meaning: "効果的な", example: "an effective strategy", exampleJa: "効果的な戦略", level: "600", category: "adjective" },
  { word: "free", meaning: "無料の、空いている", example: "free of charge", exampleJa: "無料で", level: "600", category: "adjective" },
  { word: "full", meaning: "満員の、完全な", example: "full-time position", exampleJa: "常勤のポジション", level: "600", category: "adjective" },
  { word: "local", meaning: "地元の、地域の", example: "a local supplier", exampleJa: "地元のサプライヤー", level: "600", category: "adjective" },
  { word: "positive", meaning: "前向きな、良好な", example: "positive feedback", exampleJa: "良好なフィードバック", level: "600", category: "adjective" },
  { word: "recent", meaning: "最近の", example: "recent sales figures", exampleJa: "最近の売上数字", level: "600", category: "adjective" },
  { word: "due", meaning: "期限の", example: "due by Friday", exampleJa: "金曜日が期限", level: "600", category: "adjective" },
  { word: "regarding", meaning: "〜に関して", example: "regarding your inquiry", exampleJa: "お問い合わせに関して", level: "600", category: "other" },

  // ── 730点レベル ───────────────────────────────────────
  { word: "accomplish", meaning: "達成する", example: "accomplish the goal", exampleJa: "目標を達成する", level: "730", category: "verb" },
  { word: "acquire", meaning: "取得する、買収する", example: "acquire a company", exampleJa: "会社を買収する", level: "730", category: "verb" },
  { word: "address", meaning: "対処する", example: "address the problem", exampleJa: "問題に対処する", level: "730", category: "verb" },
  { word: "adjust", meaning: "調整する", example: "adjust the price", exampleJa: "価格を調整する", level: "730", category: "verb" },
  { word: "advance", meaning: "昇進する、前進する", example: "advance to the next round", exampleJa: "次のラウンドに進む", level: "730", category: "verb" },
  { word: "allocate", meaning: "割り当てる", example: "allocate the budget", exampleJa: "予算を配分する", level: "730", category: "verb" },
  { word: "analyze", meaning: "分析する", example: "analyze the data", exampleJa: "データを分析する", level: "730", category: "verb" },
  { word: "announce", meaning: "発表する", example: "announce the results", exampleJa: "結果を発表する", level: "730", category: "verb" },
  { word: "approve", meaning: "承認する", example: "approve the proposal", exampleJa: "提案を承認する", level: "730", category: "verb" },
  { word: "assess", meaning: "評価する", example: "assess the risk", exampleJa: "リスクを評価する", level: "730", category: "verb" },
  { word: "assign", meaning: "割り当てる", example: "assign tasks to staff", exampleJa: "スタッフにタスクを割り当てる", level: "730", category: "verb" },
  { word: "assist", meaning: "支援する", example: "assist with the project", exampleJa: "プロジェクトを支援する", level: "730", category: "verb" },
  { word: "authorize", meaning: "認可する", example: "authorize the payment", exampleJa: "支払いを認可する", level: "730", category: "verb" },
  { word: "clarify", meaning: "明確にする", example: "clarify the requirements", exampleJa: "要件を明確にする", level: "730", category: "verb" },
  { word: "collaborate", meaning: "協力する", example: "collaborate on the project", exampleJa: "プロジェクトで協力する", level: "730", category: "verb" },
  { word: "compensate", meaning: "補償する", example: "compensate for the delay", exampleJa: "遅延を補償する", level: "730", category: "verb" },
  { word: "coordinate", meaning: "調整する", example: "coordinate the schedule", exampleJa: "スケジュールを調整する", level: "730", category: "verb" },
  { word: "decline", meaning: "断る、低下する", example: "decline the offer", exampleJa: "申し出を断る", level: "730", category: "verb" },
  { word: "delegate", meaning: "委任する", example: "delegate responsibilities", exampleJa: "責任を委任する", level: "730", category: "verb" },
  { word: "demonstrate", meaning: "実演する", example: "demonstrate the product", exampleJa: "製品を実演する", level: "730", category: "verb" },
  { word: "determine", meaning: "決定する", example: "determine the cause", exampleJa: "原因を特定する", level: "730", category: "verb" },
  { word: "distribute", meaning: "配布する", example: "distribute the materials", exampleJa: "資料を配布する", level: "730", category: "verb" },
  { word: "eliminate", meaning: "排除する", example: "eliminate unnecessary costs", exampleJa: "不要なコストを排除する", level: "730", category: "verb" },
  { word: "emphasize", meaning: "強調する", example: "emphasize the key points", exampleJa: "重要点を強調する", level: "730", category: "verb" },
  { word: "enhance", meaning: "強化する", example: "enhance productivity", exampleJa: "生産性を高める", level: "730", category: "verb" },
  { word: "establish", meaning: "設立する", example: "establish a partnership", exampleJa: "提携関係を築く", level: "730", category: "verb" },
  { word: "evaluate", meaning: "評価する", example: "evaluate performance", exampleJa: "業績を評価する", level: "730", category: "verb" },
  { word: "exceed", meaning: "超える", example: "exceed expectations", exampleJa: "期待を超える", level: "730", category: "verb" },
  { word: "execute", meaning: "実行する", example: "execute the plan", exampleJa: "計画を実行する", level: "730", category: "verb" },
  { word: "focus", meaning: "集中する", example: "focus on customer needs", exampleJa: "顧客ニーズに集中する", level: "730", category: "verb" },
  { word: "forecast", meaning: "予測する", example: "forecast sales growth", exampleJa: "売上成長を予測する", level: "730", category: "verb" },
  { word: "generate", meaning: "生み出す", example: "generate revenue", exampleJa: "収益を生み出す", level: "730", category: "verb" },
  { word: "identify", meaning: "特定する", example: "identify the problem", exampleJa: "問題を特定する", level: "730", category: "verb" },
  { word: "implement", meaning: "実施する", example: "implement a new system", exampleJa: "新しいシステムを導入する", level: "730", category: "verb" },
  { word: "indicate", meaning: "示す", example: "indicate the next steps", exampleJa: "次のステップを示す", level: "730", category: "verb" },
  { word: "invest", meaning: "投資する", example: "invest in technology", exampleJa: "技術に投資する", level: "730", category: "verb" },
  { word: "maintain", meaning: "維持する", example: "maintain quality standards", exampleJa: "品質基準を維持する", level: "730", category: "verb" },
  { word: "maximize", meaning: "最大化する", example: "maximize efficiency", exampleJa: "効率を最大化する", level: "730", category: "verb" },
  { word: "measure", meaning: "測定する", example: "measure performance", exampleJa: "業績を測定する", level: "730", category: "verb" },
  { word: "negotiate", meaning: "交渉する", example: "negotiate the contract", exampleJa: "契約を交渉する", level: "730", category: "verb" },
  { word: "obtain", meaning: "取得する", example: "obtain approval", exampleJa: "承認を得る", level: "730", category: "verb" },
  { word: "organize", meaning: "組織する", example: "organize a conference", exampleJa: "会議を主催する", level: "730", category: "verb" },
  { word: "oversee", meaning: "監督する", example: "oversee the operations", exampleJa: "業務を監督する", level: "730", category: "verb" },
  { word: "participate", meaning: "参加する", example: "participate in the survey", exampleJa: "調査に参加する", level: "730", category: "verb" },
  { word: "perform", meaning: "実行する、業績を上げる", example: "perform well under pressure", exampleJa: "プレッシャーの中で力を発揮する", level: "730", category: "verb" },
  { word: "promote", meaning: "昇進させる、促進する", example: "promote a product", exampleJa: "製品を宣伝する", level: "730", category: "verb" },
  { word: "propose", meaning: "提案する", example: "propose a solution", exampleJa: "解決策を提案する", level: "730", category: "verb" },
  { word: "publish", meaning: "公開する", example: "publish a report", exampleJa: "レポートを公開する", level: "730", category: "verb" },
  { word: "purchase", meaning: "購入する", example: "purchase new equipment", exampleJa: "新しい機器を購入する", level: "730", category: "verb" },
  { word: "recognize", meaning: "認識する、表彰する", example: "recognize outstanding work", exampleJa: "優れた仕事を表彰する", level: "730", category: "verb" },
  { word: "resolve", meaning: "解決する", example: "resolve a complaint", exampleJa: "苦情を解決する", level: "730", category: "verb" },
  { word: "retain", meaning: "維持する、保持する", example: "retain top talent", exampleJa: "優秀な人材を確保する", level: "730", category: "verb" },
  { word: "transfer", meaning: "転送する、異動させる", example: "transfer to another office", exampleJa: "他の支社に異動する", level: "730", category: "verb" },
  { word: "utilize", meaning: "活用する", example: "utilize available resources", exampleJa: "利用可能なリソースを活用する", level: "730", category: "verb" },
  { word: "verify", meaning: "確認する", example: "verify the information", exampleJa: "情報を確認する", level: "730", category: "verb" },
  { word: "achievement", meaning: "達成、業績", example: "a major achievement", exampleJa: "大きな業績", level: "730", category: "noun" },
  { word: "agreement", meaning: "合意、契約", example: "reach an agreement", exampleJa: "合意に達する", level: "730", category: "noun" },
  { word: "application", meaning: "申請、応募書類", example: "submit an application", exampleJa: "応募書類を提出する", level: "730", category: "noun" },
  { word: "approval", meaning: "承認", example: "obtain approval", exampleJa: "承認を得る", level: "730", category: "noun" },
  { word: "attachment", meaning: "添付ファイル", example: "see the attachment", exampleJa: "添付ファイルを参照", level: "730", category: "noun" },
  { word: "attendance", meaning: "出席", example: "attendance is required", exampleJa: "出席が必要", level: "730", category: "noun" },
  { word: "authority", meaning: "権限", example: "have the authority", exampleJa: "権限を持つ", level: "730", category: "noun" },
  { word: "certificate", meaning: "証明書", example: "a completion certificate", exampleJa: "修了証明書", level: "730", category: "noun" },
  { word: "commitment", meaning: "コミットメント、約束", example: "show commitment", exampleJa: "コミットメントを示す", level: "730", category: "noun" },
  { word: "committee", meaning: "委員会", example: "the steering committee", exampleJa: "運営委員会", level: "730", category: "noun" },
  { word: "compensation", meaning: "報酬、補償", example: "a competitive compensation", exampleJa: "競争力のある報酬", level: "730", category: "noun" },
  { word: "conference", meaning: "会議、会合", example: "an annual conference", exampleJa: "年次会議", level: "730", category: "noun" },
  { word: "conflict", meaning: "衝突、対立", example: "a scheduling conflict", exampleJa: "スケジュールの競合", level: "730", category: "noun" },
  { word: "contribution", meaning: "貢献", example: "make a contribution", exampleJa: "貢献する", level: "730", category: "noun" },
  { word: "decision", meaning: "決定", example: "make a final decision", exampleJa: "最終決定を下す", level: "730", category: "noun" },
  { word: "demand", meaning: "需要", example: "growing demand", exampleJa: "高まる需要", level: "730", category: "noun" },
  { word: "description", meaning: "説明、記述", example: "a job description", exampleJa: "職務記述書", level: "730", category: "noun" },
  { word: "division", meaning: "部門、事業部", example: "the marketing division", exampleJa: "マーケティング事業部", level: "730", category: "noun" },
  { word: "efficiency", meaning: "効率", example: "improve efficiency", exampleJa: "効率を改善する", level: "730", category: "noun" },
  { word: "expansion", meaning: "拡大", example: "business expansion", exampleJa: "事業拡大", level: "730", category: "noun" },
  { word: "extension", meaning: "延長、内線", example: "an extension of the deadline", exampleJa: "締め切りの延長", level: "730", category: "noun" },
  { word: "forecast", meaning: "予測、見通し", example: "the sales forecast", exampleJa: "売上予測", level: "730", category: "noun" },
  { word: "fund", meaning: "資金", example: "secure additional funds", exampleJa: "追加資金を確保する", level: "730", category: "noun" },
  { word: "goal", meaning: "目標", example: "set a goal", exampleJa: "目標を設定する", level: "730", category: "noun" },
  { word: "growth", meaning: "成長", example: "drive growth", exampleJa: "成長を促進する", level: "730", category: "noun" },
  { word: "guideline", meaning: "ガイドライン", example: "follow the guidelines", exampleJa: "ガイドラインに従う", level: "730", category: "noun" },
  { word: "impact", meaning: "影響", example: "a positive impact", exampleJa: "プラスの影響", level: "730", category: "noun" },
  { word: "income", meaning: "収入", example: "annual income", exampleJa: "年間収入", level: "730", category: "noun" },
  { word: "initiative", meaning: "取り組み、主導権", example: "a cost-saving initiative", exampleJa: "コスト削減の取り組み", level: "730", category: "noun" },
  { word: "inventory", meaning: "在庫", example: "manage inventory", exampleJa: "在庫を管理する", level: "730", category: "noun" },
  { word: "investment", meaning: "投資", example: "return on investment", exampleJa: "投資対効果", level: "730", category: "noun" },
  { word: "leadership", meaning: "リーダーシップ", example: "strong leadership", exampleJa: "強いリーダーシップ", level: "730", category: "noun" },
  { word: "margin", meaning: "利益率、余白", example: "a profit margin", exampleJa: "利益率", level: "730", category: "noun" },
  { word: "material", meaning: "資料、素材", example: "training materials", exampleJa: "研修資料", level: "730", category: "noun" },
  { word: "motivation", meaning: "モチベーション", example: "boost motivation", exampleJa: "モチベーションを高める", level: "730", category: "noun" },
  { word: "network", meaning: "ネットワーク、人脈", example: "build a network", exampleJa: "人脈を築く", level: "730", category: "noun" },
  { word: "objective", meaning: "目標、目的", example: "meet the objectives", exampleJa: "目標を達成する", level: "730", category: "noun" },
  { word: "output", meaning: "産出量、成果", example: "increase output", exampleJa: "産出量を増やす", level: "730", category: "noun" },
  { word: "performance", meaning: "業績、パフォーマンス", example: "evaluate performance", exampleJa: "業績を評価する", level: "730", category: "noun" },
  { word: "procedure", meaning: "手順", example: "follow the procedure", exampleJa: "手順に従う", level: "730", category: "noun" },
  { word: "qualification", meaning: "資格", example: "the required qualifications", exampleJa: "必要な資格", level: "730", category: "noun" },
  { word: "quarter", meaning: "四半期", example: "in the third quarter", exampleJa: "第3四半期に", level: "730", category: "noun" },
  { word: "regulation", meaning: "規制、規則", example: "comply with regulations", exampleJa: "規制を遵守する", level: "730", category: "noun" },
  { word: "reputation", meaning: "評判", example: "a strong reputation", exampleJa: "高い評判", level: "730", category: "noun" },
  { word: "resource", meaning: "資源、リソース", example: "allocate resources", exampleJa: "リソースを配分する", level: "730", category: "noun" },
  { word: "revenue", meaning: "収益、売上", example: "increase revenue", exampleJa: "収益を増やす", level: "730", category: "noun" },
  { word: "sector", meaning: "部門、分野", example: "the financial sector", exampleJa: "金融分野", level: "730", category: "noun" },
  { word: "solution", meaning: "解決策", example: "find a solution", exampleJa: "解決策を見つける", level: "730", category: "noun" },
  { word: "statement", meaning: "声明、明細書", example: "a financial statement", exampleJa: "財務諸表", level: "730", category: "noun" },
  { word: "strategy", meaning: "戦略", example: "develop a strategy", exampleJa: "戦略を立てる", level: "730", category: "noun" },
  { word: "supplier", meaning: "サプライヤー", example: "a reliable supplier", exampleJa: "信頼できるサプライヤー", level: "730", category: "noun" },
  { word: "survey", meaning: "調査、アンケート", example: "conduct a survey", exampleJa: "調査を実施する", level: "730", category: "noun" },
  { word: "timeline", meaning: "タイムライン、期日", example: "set a timeline", exampleJa: "タイムラインを設定する", level: "730", category: "noun" },
  { word: "transaction", meaning: "取引", example: "complete a transaction", exampleJa: "取引を完了する", level: "730", category: "noun" },
  { word: "trend", meaning: "傾向、トレンド", example: "a growing trend", exampleJa: "高まるトレンド", level: "730", category: "noun" },
  { word: "vendor", meaning: "販売業者、ベンダー", example: "select a vendor", exampleJa: "ベンダーを選ぶ", level: "730", category: "noun" },
  { word: "workforce", meaning: "労働力、従業員", example: "a skilled workforce", exampleJa: "熟練した労働力", level: "730", category: "noun" },
  { word: "adequate", meaning: "十分な", example: "adequate preparation", exampleJa: "十分な準備", level: "730", category: "adjective" },
  { word: "annual", meaning: "毎年の、年次の", example: "the annual report", exampleJa: "年次報告書", level: "730", category: "adjective" },
  { word: "competitive", meaning: "競争力のある", example: "a competitive price", exampleJa: "競争力のある価格", level: "730", category: "adjective" },
  { word: "confidential", meaning: "機密の", example: "confidential information", exampleJa: "機密情報", level: "730", category: "adjective" },
  { word: "convenient", meaning: "便利な", example: "a convenient location", exampleJa: "便利な場所", level: "730", category: "adjective" },
  { word: "efficient", meaning: "効率的な", example: "an efficient process", exampleJa: "効率的なプロセス", level: "730", category: "adjective" },
  { word: "eligible", meaning: "資格がある", example: "eligible for promotion", exampleJa: "昇進の資格がある", level: "730", category: "adjective" },
  { word: "essential", meaning: "必須の", example: "essential skills", exampleJa: "必須スキル", level: "730", category: "adjective" },
  { word: "flexible", meaning: "柔軟な", example: "a flexible schedule", exampleJa: "柔軟なスケジュール", level: "730", category: "adjective" },
  { word: "mandatory", meaning: "義務的な", example: "mandatory training", exampleJa: "必修研修", level: "730", category: "adjective" },
  { word: "productive", meaning: "生産的な", example: "a productive meeting", exampleJa: "生産的な会議", level: "730", category: "adjective" },
  { word: "reliable", meaning: "信頼できる", example: "a reliable partner", exampleJa: "信頼できるパートナー", level: "730", category: "adjective" },
  { word: "responsible", meaning: "責任がある", example: "responsible for the project", exampleJa: "プロジェクトの責任者", level: "730", category: "adjective" },
  { word: "significant", meaning: "重要な、著しい", example: "a significant improvement", exampleJa: "著しい改善", level: "730", category: "adjective" },
  { word: "suitable", meaning: "適切な", example: "suitable for the role", exampleJa: "その役割に適した", level: "730", category: "adjective" },
  { word: "temporary", meaning: "一時的な", example: "a temporary position", exampleJa: "一時的なポジション", level: "730", category: "adjective" },
  { word: "despite", meaning: "〜にもかかわらず", example: "despite the challenges", exampleJa: "課題にもかかわらず", level: "730", category: "other" },
  { word: "throughout", meaning: "〜を通じて", example: "throughout the year", exampleJa: "一年を通じて", level: "730", category: "other" },
  { word: "unless", meaning: "〜でない限り", example: "unless otherwise stated", exampleJa: "特に記載がない限り", level: "730", category: "other" },

  // ── 860点レベル ───────────────────────────────────────
  { word: "accommodate", meaning: "収容する、対応する", example: "accommodate all requests", exampleJa: "あらゆる要求に対応する", level: "860", category: "verb" },
  { word: "accelerate", meaning: "加速する", example: "accelerate the process", exampleJa: "プロセスを加速させる", level: "860", category: "verb" },
  { word: "anticipate", meaning: "予期する", example: "anticipate future demand", exampleJa: "将来の需要を予測する", level: "860", category: "verb" },
  { word: "attribute", meaning: "〜のせいにする、帰する", example: "attribute success to teamwork", exampleJa: "成功をチームワークのおかげとする", level: "860", category: "verb" },
  { word: "comply", meaning: "従う", example: "comply with regulations", exampleJa: "規制に従う", level: "860", category: "verb" },
  { word: "consolidate", meaning: "統合する", example: "consolidate the departments", exampleJa: "部門を統合する", level: "860", category: "verb" },
  { word: "convene", meaning: "召集する", example: "convene a meeting", exampleJa: "会議を召集する", level: "860", category: "verb" },
  { word: "defer", meaning: "延期する", example: "defer the decision", exampleJa: "決定を延期する", level: "860", category: "verb" },
  { word: "depreciate", meaning: "減価償却する", example: "depreciate over five years", exampleJa: "5年かけて償却する", level: "860", category: "verb" },
  { word: "designate", meaning: "指定する", example: "designate a parking space", exampleJa: "駐車スペースを指定する", level: "860", category: "verb" },
  { word: "differentiate", meaning: "差別化する", example: "differentiate from competitors", exampleJa: "競合他社と差別化する", level: "860", category: "verb" },
  { word: "disclose", meaning: "開示する", example: "disclose financial information", exampleJa: "財務情報を開示する", level: "860", category: "verb" },
  { word: "dispatch", meaning: "派遣する、発送する", example: "dispatch a technician", exampleJa: "技術者を派遣する", level: "860", category: "verb" },
  { word: "diversify", meaning: "多様化する", example: "diversify the portfolio", exampleJa: "ポートフォリオを多様化する", level: "860", category: "verb" },
  { word: "expedite", meaning: "迅速に処理する", example: "expedite the order", exampleJa: "注文を急いで処理する", level: "860", category: "verb" },
  { word: "facilitate", meaning: "促進する", example: "facilitate the discussion", exampleJa: "議論を促進する", level: "860", category: "verb" },
  { word: "fluctuate", meaning: "変動する", example: "prices fluctuate daily", exampleJa: "価格が毎日変動する", level: "860", category: "verb" },
  { word: "incur", meaning: "（費用などを）被る", example: "incur additional costs", exampleJa: "追加費用が発生する", level: "860", category: "verb" },
  { word: "initiate", meaning: "開始する", example: "initiate a new project", exampleJa: "新しいプロジェクトを開始する", level: "860", category: "verb" },
  { word: "innovate", meaning: "革新する", example: "innovate constantly", exampleJa: "絶えず革新する", level: "860", category: "verb" },
  { word: "integrate", meaning: "統合する", example: "integrate the two systems", exampleJa: "2つのシステムを統合する", level: "860", category: "verb" },
  { word: "leverage", meaning: "活用する", example: "leverage existing resources", exampleJa: "既存リソースを活用する", level: "860", category: "verb" },
  { word: "mitigate", meaning: "軽減する", example: "mitigate the risk", exampleJa: "リスクを軽減する", level: "860", category: "verb" },
  { word: "monitor", meaning: "監視する", example: "monitor the progress", exampleJa: "進捗を監視する", level: "860", category: "verb" },
  { word: "optimize", meaning: "最適化する", example: "optimize the workflow", exampleJa: "業務フローを最適化する", level: "860", category: "verb" },
  { word: "outsource", meaning: "外注する", example: "outsource the work", exampleJa: "仕事を外注する", level: "860", category: "verb" },
  { word: "prioritize", meaning: "優先する", example: "prioritize urgent tasks", exampleJa: "緊急タスクを優先する", level: "860", category: "verb" },
  { word: "reimburse", meaning: "払い戻す", example: "reimburse travel expenses", exampleJa: "出張費を払い戻す", level: "860", category: "verb" },
  { word: "restructure", meaning: "再編する", example: "restructure the organization", exampleJa: "組織を再編する", level: "860", category: "verb" },
  { word: "streamline", meaning: "合理化する", example: "streamline the process", exampleJa: "プロセスを合理化する", level: "860", category: "verb" },
  { word: "sustain", meaning: "維持する", example: "sustain growth", exampleJa: "成長を維持する", level: "860", category: "verb" },
  { word: "terminate", meaning: "終了する、解雇する", example: "terminate the contract", exampleJa: "契約を解除する", level: "860", category: "verb" },
  { word: "waive", meaning: "放棄する", example: "waive the fee", exampleJa: "手数料を免除する", level: "860", category: "verb" },
  { word: "acquisition", meaning: "買収、取得", example: "a major acquisition", exampleJa: "大型買収", level: "860", category: "noun" },
  { word: "amendment", meaning: "修正、改正", example: "propose an amendment", exampleJa: "修正案を提出する", level: "860", category: "noun" },
  { word: "audit", meaning: "監査", example: "conduct an audit", exampleJa: "監査を実施する", level: "860", category: "noun" },
  { word: "benchmark", meaning: "基準、目安", example: "set a benchmark", exampleJa: "基準を設定する", level: "860", category: "noun" },
  { word: "clause", meaning: "条項", example: "a contract clause", exampleJa: "契約条項", level: "860", category: "noun" },
  { word: "compliance", meaning: "コンプライアンス、遵守", example: "ensure compliance", exampleJa: "コンプライアンスを確保する", level: "860", category: "noun" },
  { word: "constraint", meaning: "制約", example: "budget constraints", exampleJa: "予算の制約", level: "860", category: "noun" },
  { word: "contingency", meaning: "不測の事態", example: "a contingency plan", exampleJa: "緊急時の対応計画", level: "860", category: "noun" },
  { word: "criterion", meaning: "基準", example: "the selection criterion", exampleJa: "選考基準", level: "860", category: "noun" },
  { word: "deficit", meaning: "赤字、不足", example: "a budget deficit", exampleJa: "財政赤字", level: "860", category: "noun" },
  { word: "disruption", meaning: "混乱、中断", example: "minimize disruption", exampleJa: "混乱を最小限に抑える", level: "860", category: "noun" },
  { word: "fluctuation", meaning: "変動", example: "price fluctuations", exampleJa: "価格変動", level: "860", category: "noun" },
  { word: "framework", meaning: "枠組み", example: "a legal framework", exampleJa: "法的枠組み", level: "860", category: "noun" },
  { word: "incentive", meaning: "インセンティブ、動機", example: "offer an incentive", exampleJa: "インセンティブを提供する", level: "860", category: "noun" },
  { word: "infrastructure", meaning: "インフラ", example: "upgrade the infrastructure", exampleJa: "インフラを整備する", level: "860", category: "noun" },
  { word: "leverage", meaning: "てこ、影響力", example: "use as leverage", exampleJa: "交渉材料として使う", level: "860", category: "noun" },
  { word: "liability", meaning: "負債、法的責任", example: "limit liability", exampleJa: "責任を制限する", level: "860", category: "noun" },
  { word: "logistics", meaning: "物流", example: "manage logistics", exampleJa: "物流を管理する", level: "860", category: "noun" },
  { word: "merger", meaning: "合併", example: "a corporate merger", exampleJa: "企業合併", level: "860", category: "noun" },
  { word: "milestone", meaning: "節目、重要な段階", example: "reach a milestone", exampleJa: "節目を迎える", level: "860", category: "noun" },
  { word: "overhead", meaning: "経費、諸経費", example: "reduce overhead costs", exampleJa: "諸経費を削減する", level: "860", category: "noun" },
  { word: "portfolio", meaning: "ポートフォリオ", example: "a diversified portfolio", exampleJa: "分散したポートフォリオ", level: "860", category: "noun" },
  { word: "procurement", meaning: "調達", example: "streamline procurement", exampleJa: "調達を合理化する", level: "860", category: "noun" },
  { word: "prospect", meaning: "見込み客、見通し", example: "a promising prospect", exampleJa: "有望な見込み客", level: "860", category: "noun" },
  { word: "prototype", meaning: "試作品", example: "develop a prototype", exampleJa: "試作品を開発する", level: "860", category: "noun" },
  { word: "provision", meaning: "規定、条項", example: "make provisions for", exampleJa: "〜の備えをする", level: "860", category: "noun" },
  { word: "reimbursement", meaning: "払い戻し", example: "expense reimbursement", exampleJa: "経費の払い戻し", level: "860", category: "noun" },
  { word: "retention", meaning: "保持、定着率", example: "improve staff retention", exampleJa: "スタッフの定着率を上げる", level: "860", category: "noun" },
  { word: "subsidiary", meaning: "子会社", example: "a wholly-owned subsidiary", exampleJa: "完全子会社", level: "860", category: "noun" },
  { word: "turnover", meaning: "売上高、離職率", example: "reduce staff turnover", exampleJa: "離職率を下げる", level: "860", category: "noun" },
  { word: "valuation", meaning: "評価額", example: "a company valuation", exampleJa: "企業評価額", level: "860", category: "noun" },
  { word: "viable", meaning: "実行可能な", example: "a viable option", exampleJa: "実行可能な選択肢", level: "860", category: "adjective" },
  { word: "comprehensive", meaning: "包括的な", example: "a comprehensive plan", exampleJa: "包括的な計画", level: "860", category: "adjective" },
  { word: "consecutive", meaning: "連続した", example: "three consecutive quarters", exampleJa: "3四半期連続", level: "860", category: "adjective" },
  { word: "domestic", meaning: "国内の", example: "domestic and international", exampleJa: "国内外", level: "860", category: "adjective" },
  { word: "exclusive", meaning: "独占的な、限定的な", example: "an exclusive contract", exampleJa: "独占契約", level: "860", category: "adjective" },
  { word: "imminent", meaning: "差し迫った", example: "an imminent deadline", exampleJa: "差し迫った締め切り", level: "860", category: "adjective" },
  { word: "preliminary", meaning: "予備的な", example: "preliminary results", exampleJa: "予備的な結果", level: "860", category: "adjective" },
  { word: "stringent", meaning: "厳しい", example: "stringent requirements", exampleJa: "厳しい要件", level: "860", category: "adjective" },
  { word: "substantial", meaning: "かなりの", example: "a substantial increase", exampleJa: "かなりの増加", level: "860", category: "adjective" },
  { word: "sustainable", meaning: "持続可能な", example: "sustainable growth", exampleJa: "持続可能な成長", level: "860", category: "adjective" },
  { word: "transparent", meaning: "透明な", example: "transparent pricing", exampleJa: "透明な価格設定", level: "860", category: "adjective" },
  { word: "pursuant", meaning: "〜に従って", example: "pursuant to the agreement", exampleJa: "合意に従って", level: "860", category: "other" },
  { word: "hereby", meaning: "これにより", example: "hereby notify you", exampleJa: "これにより通知します", level: "860", category: "other" },
  { word: "notwithstanding", meaning: "〜にもかかわらず", example: "notwithstanding the delay", exampleJa: "遅延にもかかわらず", level: "860", category: "other" },

  // ── 990点レベル ───────────────────────────────────────
  { word: "arbitrate", meaning: "仲裁する", example: "arbitrate the dispute", exampleJa: "紛争を仲裁する", level: "990", category: "verb" },
  { word: "ascertain", meaning: "確認する、突き止める", example: "ascertain the facts", exampleJa: "事実を確認する", level: "990", category: "verb" },
  { word: "circumvent", meaning: "回避する", example: "circumvent the rules", exampleJa: "規則を回避する", level: "990", category: "verb" },
  { word: "codify", meaning: "成文化する", example: "codify the regulations", exampleJa: "規制を成文化する", level: "990", category: "verb" },
  { word: "corroborate", meaning: "裏付ける", example: "corroborate the findings", exampleJa: "調査結果を裏付ける", level: "990", category: "verb" },
  { word: "delineate", meaning: "明確に述べる", example: "delineate responsibilities", exampleJa: "責任範囲を明確にする", level: "990", category: "verb" },
  { word: "disseminate", meaning: "普及させる", example: "disseminate the information", exampleJa: "情報を広める", level: "990", category: "verb" },
  { word: "divulge", meaning: "漏らす、開示する", example: "divulge confidential data", exampleJa: "機密データを漏らす", level: "990", category: "verb" },
  { word: "engender", meaning: "生み出す", example: "engender trust", exampleJa: "信頼を生み出す", level: "990", category: "verb" },
  { word: "enumerate", meaning: "列挙する", example: "enumerate the conditions", exampleJa: "条件を列挙する", level: "990", category: "verb" },
  { word: "exacerbate", meaning: "悪化させる", example: "exacerbate the situation", exampleJa: "状況を悪化させる", level: "990", category: "verb" },
  { word: "forestall", meaning: "先手を打つ", example: "forestall potential problems", exampleJa: "潜在的な問題を未然に防ぐ", level: "990", category: "verb" },
  { word: "galvanize", meaning: "活性化させる", example: "galvanize the team", exampleJa: "チームを奮起させる", level: "990", category: "verb" },
  { word: "impede", meaning: "妨げる", example: "impede progress", exampleJa: "進歩を妨げる", level: "990", category: "verb" },
  { word: "inaugurate", meaning: "就任させる、開始する", example: "inaugurate a new policy", exampleJa: "新しい政策を開始する", level: "990", category: "verb" },
  { word: "indemnify", meaning: "補償する", example: "indemnify against losses", exampleJa: "損失を補償する", level: "990", category: "verb" },
  { word: "mandate", meaning: "命じる", example: "mandate compliance", exampleJa: "コンプライアンスを義務付ける", level: "990", category: "verb" },
  { word: "obviate", meaning: "取り除く", example: "obviate the need for", exampleJa: "〜の必要性をなくす", level: "990", category: "verb" },
  { word: "preclude", meaning: "除外する、妨げる", example: "preclude further action", exampleJa: "それ以上の行動を妨げる", level: "990", category: "verb" },
  { word: "promulgate", meaning: "公布する", example: "promulgate new rules", exampleJa: "新しい規則を公布する", level: "990", category: "verb" },
  { word: "ratify", meaning: "批准する", example: "ratify the treaty", exampleJa: "条約を批准する", level: "990", category: "verb" },
  { word: "reconcile", meaning: "和解させる、照合する", example: "reconcile the accounts", exampleJa: "勘定を照合する", level: "990", category: "verb" },
  { word: "rectify", meaning: "修正する", example: "rectify the error", exampleJa: "誤りを修正する", level: "990", category: "verb" },
  { word: "remunerate", meaning: "報酬を払う", example: "remunerate fairly", exampleJa: "公正に報酬を支払う", level: "990", category: "verb" },
  { word: "rescind", meaning: "廃止する", example: "rescind the decision", exampleJa: "決定を撤回する", level: "990", category: "verb" },
  { word: "sequester", meaning: "差し押さえる", example: "sequester assets", exampleJa: "資産を差し押さえる", level: "990", category: "verb" },
  { word: "stipulate", meaning: "規定する", example: "stipulate the terms", exampleJa: "条件を規定する", level: "990", category: "verb" },
  { word: "supersede", meaning: "取って代わる", example: "supersede the old policy", exampleJa: "旧方針に取って代わる", level: "990", category: "verb" },
  { word: "adjudicate", meaning: "判定する", example: "adjudicate the claim", exampleJa: "請求を判定する", level: "990", category: "verb" },
  { word: "perpetuate", meaning: "永続させる", example: "perpetuate the practice", exampleJa: "慣行を永続させる", level: "990", category: "verb" },
  { word: "accrual", meaning: "累積、発生", example: "accrual basis accounting", exampleJa: "発生主義会計", level: "990", category: "noun" },
  { word: "arbitration", meaning: "仲裁", example: "settle through arbitration", exampleJa: "仲裁で解決する", level: "990", category: "noun" },
  { word: "caveat", meaning: "警告、条件", example: "with one caveat", exampleJa: "一つの条件付きで", level: "990", category: "noun" },
  { word: "collateral", meaning: "担保", example: "provide collateral", exampleJa: "担保を提供する", level: "990", category: "noun" },
  { word: "consortium", meaning: "コンソーシアム、共同体", example: "form a consortium", exampleJa: "コンソーシアムを結成する", level: "990", category: "noun" },
  { word: "encumbrance", meaning: "担保権、障害", example: "free from encumbrance", exampleJa: "担保権から解放される", level: "990", category: "noun" },
  { word: "fiduciary", meaning: "受託者、信任の", example: "fiduciary responsibility", exampleJa: "受託者責任", level: "990", category: "noun" },
  { word: "indemnity", meaning: "損害補償", example: "an indemnity clause", exampleJa: "損害補償条項", level: "990", category: "noun" },
  { word: "injunction", meaning: "差し止め命令", example: "seek an injunction", exampleJa: "差し止め命令を求める", level: "990", category: "noun" },
  { word: "insolvency", meaning: "支払い不能", example: "file for insolvency", exampleJa: "支払い不能を申請する", level: "990", category: "noun" },
  { word: "liquidation", meaning: "清算", example: "enter liquidation", exampleJa: "清算手続きに入る", level: "990", category: "noun" },
  { word: "moratorium", meaning: "一時停止、猶予期間", example: "a debt moratorium", exampleJa: "債務支払い猶予", level: "990", category: "noun" },
  { word: "nexus", meaning: "関連、つながり", example: "a nexus of relationships", exampleJa: "関係のつながり", level: "990", category: "noun" },
  { word: "prerogative", meaning: "特権", example: "management's prerogative", exampleJa: "経営者の特権", level: "990", category: "noun" },
  { word: "proviso", meaning: "条件、但し書き", example: "with the proviso that", exampleJa: "〜という条件で", level: "990", category: "noun" },
  { word: "recourse", meaning: "手段、頼りにすること", example: "have recourse to arbitration", exampleJa: "仲裁に訴える", level: "990", category: "noun" },
  { word: "solvency", meaning: "支払い能力", example: "maintain solvency", exampleJa: "支払い能力を維持する", level: "990", category: "noun" },
  { word: "amortization", meaning: "償却", example: "amortization schedule", exampleJa: "償還スケジュール", level: "990", category: "noun" },
  { word: "commensurate", meaning: "相応の", example: "commensurate with experience", exampleJa: "経験に相応した", level: "990", category: "adjective" },
  { word: "exigent", meaning: "緊急の", example: "exigent circumstances", exampleJa: "緊急の状況", level: "990", category: "adjective" },
  { word: "germane", meaning: "関連する、適切な", example: "germane to the discussion", exampleJa: "議論に関連する", level: "990", category: "adjective" },
  { word: "insolvent", meaning: "支払い不能の", example: "declared insolvent", exampleJa: "支払い不能と宣告された", level: "990", category: "adjective" },
  { word: "onerous", meaning: "厄介な、負担の多い", example: "onerous regulations", exampleJa: "厄介な規制", level: "990", category: "adjective" },
  { word: "perfunctory", meaning: "形式的な", example: "a perfunctory review", exampleJa: "形式的な審査", level: "990", category: "adjective" },
  { word: "solvent", meaning: "支払い能力のある", example: "remain solvent", exampleJa: "支払い能力を保つ", level: "990", category: "adjective" },
];
