const WORDS = [
  { word: "abandon", meaning: "捨てる、放棄する", example: "The company decided to abandon the project due to budget cuts." },
  { word: "accelerate", meaning: "加速する、促進する", example: "The new strategy will accelerate our growth in the market." },
  { word: "accommodate", meaning: "収容する、対応する", example: "The hotel can accommodate up to 500 guests." },
  { word: "accomplish", meaning: "達成する、成し遂げる", example: "She accomplished all her goals for the quarter." },
  { word: "accurate", meaning: "正確な", example: "Please make sure the report is accurate before submitting it." },
  { word: "acquire", meaning: "取得する、買収する", example: "The firm acquired three smaller companies last year." },
  { word: "address", meaning: "対処する、取り組む", example: "We need to address the customer complaints immediately." },
  { word: "adequate", meaning: "十分な、適切な", example: "Make sure you have adequate time to complete the project." },
  { word: "adjacent", meaning: "隣接した", example: "The meeting room is adjacent to the main office." },
  { word: "adjust", meaning: "調整する", example: "You may need to adjust your schedule to meet the deadline." },
  { word: "administration", meaning: "管理、行政", example: "The administration team handles all office logistics." },
  { word: "advance", meaning: "前進する、昇進させる", example: "She was advanced to senior manager after five years." },
  { word: "advantage", meaning: "利点、優位性", example: "Our product has a clear advantage over competitors." },
  { word: "agenda", meaning: "議題、予定", example: "Please review the agenda before the meeting." },
  { word: "allocate", meaning: "割り当てる、配分する", example: "We need to allocate more resources to the marketing team." },
  { word: "alternative", meaning: "代替の、選択肢", example: "Is there an alternative solution to this problem?" },
  { word: "analyze", meaning: "分析する", example: "The team will analyze the sales data from last quarter." },
  { word: "announce", meaning: "発表する、告知する", example: "The CEO will announce the new policy tomorrow." },
  { word: "annual", meaning: "年次の、毎年の", example: "The annual report will be published next month." },
  { word: "anticipate", meaning: "予期する、見込む", example: "We anticipate strong sales growth this year." },
  { word: "apply", meaning: "応募する、申請する", example: "She decided to apply for the marketing position." },
  { word: "appoint", meaning: "任命する、指定する", example: "The board appointed a new CEO last week." },
  { word: "approve", meaning: "承認する", example: "The manager approved the budget proposal." },
  { word: "assess", meaning: "評価する、査定する", example: "We need to assess the risks before proceeding." },
  { word: "assign", meaning: "割り当てる、任命する", example: "The project was assigned to the senior team." },
  { word: "assist", meaning: "支援する、手伝う", example: "Our staff will assist you with the registration process." },
  { word: "assume", meaning: "仮定する、引き受ける", example: "I assume you have reviewed the contract." },
  { word: "authorize", meaning: "認可する、権限を与える", example: "Only the director can authorize such expenses." },
  { word: "available", meaning: "利用可能な、空いている", example: "Is the conference room available on Friday?" },
  { word: "aware", meaning: "気づいている、知っている", example: "Please be aware of the new company policies." },
  { word: "benefit", meaning: "利益、恩恵", example: "The new software offers many benefits to our team." },
  { word: "budget", meaning: "予算", example: "We need to stay within the project budget." },
  { word: "calculate", meaning: "計算する", example: "Please calculate the total cost of the project." },
  { word: "candidate", meaning: "候補者", example: "We interviewed five candidates for the position." },
  { word: "capable", meaning: "能力がある", example: "She is capable of managing a large team." },
  { word: "capacity", meaning: "容量、能力", example: "The factory is operating at full capacity." },
  { word: "collaborate", meaning: "協力する", example: "The two departments will collaborate on the project." },
  { word: "compensate", meaning: "補償する、賃金を支払う", example: "Employees are compensated for overtime work." },
  { word: "competitive", meaning: "競争力のある", example: "We offer competitive salaries and benefits." },
  { word: "complete", meaning: "完了する、完全な", example: "Please complete the form and submit it by Friday." },
  { word: "comprehensive", meaning: "包括的な", example: "The report provides a comprehensive overview of the market." },
  { word: "confirm", meaning: "確認する", example: "Please confirm your attendance at the conference." },
  { word: "consider", meaning: "検討する", example: "We will consider all options before deciding." },
  { word: "contract", meaning: "契約", example: "Both parties signed the contract yesterday." },
  { word: "contribute", meaning: "貢献する", example: "Everyone should contribute to the team's success." },
  { word: "convenient", meaning: "便利な", example: "Is it convenient for you to meet on Monday?" },
  { word: "coordinate", meaning: "調整する、連携する", example: "She coordinates all the logistics for the events." },
  { word: "crucial", meaning: "重要な、決定的な", example: "Customer feedback is crucial for product development." },
  { word: "current", meaning: "現在の、最新の", example: "Please share the current version of the report." },
  { word: "deadline", meaning: "締め切り", example: "We must meet the project deadline." },
  { word: "decrease", meaning: "減少する", example: "Sales have decreased by 10% this quarter." },
  { word: "delay", meaning: "遅延、遅らせる", example: "The shipment was delayed due to bad weather." },
  { word: "delegate", meaning: "委任する、代表者", example: "He learned to delegate tasks to his team members." },
  { word: "deliver", meaning: "配達する、達成する", example: "We guarantee to deliver your order within three days." },
  { word: "demonstrate", meaning: "実演する、証明する", example: "She demonstrated how to use the new software." },
  { word: "department", meaning: "部門、部署", example: "The marketing department will lead the campaign." },
  { word: "determine", meaning: "決定する、判断する", example: "We need to determine the root cause of the problem." },
  { word: "develop", meaning: "開発する、発展させる", example: "The team is developing a new mobile application." },
  { word: "discount", meaning: "割引", example: "We offer a 10% discount for bulk orders." },
  { word: "distribute", meaning: "配布する、配給する", example: "The materials will be distributed before the meeting." },
  { word: "document", meaning: "文書化する、書類", example: "Please document all changes made to the system." },
  { word: "efficient", meaning: "効率的な", example: "The new process is more efficient than the old one." },
  { word: "eliminate", meaning: "排除する、なくす", example: "We need to eliminate unnecessary expenses." },
  { word: "emphasize", meaning: "強調する", example: "The manager emphasized the importance of teamwork." },
  { word: "employ", meaning: "雇用する", example: "The company employs over 500 people." },
  { word: "encourage", meaning: "奨励する、励ます", example: "We encourage all employees to share their ideas." },
  { word: "enhance", meaning: "強化する、高める", example: "The training program will enhance your skills." },
  { word: "establish", meaning: "設立する、確立する", example: "The company was established in 1995." },
  { word: "evaluate", meaning: "評価する", example: "We will evaluate all proposals by next week." },
  { word: "exceed", meaning: "超える", example: "Our sales exceeded expectations this quarter." },
  { word: "execute", meaning: "実行する、実施する", example: "The team successfully executed the marketing plan." },
  { word: "expand", meaning: "拡大する", example: "We plan to expand our operations to Asia." },
  { word: "experience", meaning: "経験", example: "She has ten years of experience in finance." },
  { word: "facilitate", meaning: "促進する、容易にする", example: "The new software facilitates data sharing." },
  { word: "flexible", meaning: "柔軟な", example: "We offer flexible working hours." },
  { word: "focus", meaning: "集中する、重点を置く", example: "This quarter, we will focus on customer retention." },
  { word: "forecast", meaning: "予測する、見通し", example: "The sales forecast looks positive for next year." },
  { word: "generate", meaning: "生み出す、発生させる", example: "The new product line generated significant revenue." },
  { word: "guarantee", meaning: "保証する", example: "We guarantee delivery within 48 hours." },
  { word: "implement", meaning: "実施する、導入する", example: "The new policy will be implemented next month." },
  { word: "improve", meaning: "改善する", example: "We are working to improve customer service." },
  { word: "increase", meaning: "増加する、増やす", example: "We aim to increase our market share by 15%." },
  { word: "indicate", meaning: "示す、指示する", example: "The data indicates a strong upward trend." },
  { word: "initiative", meaning: "主導権、取り組み", example: "The CEO launched a new cost-saving initiative." },
  { word: "innovate", meaning: "革新する", example: "We must innovate to stay ahead of the competition." },
  { word: "integrate", meaning: "統合する", example: "The two systems will be integrated next quarter." },
  { word: "invest", meaning: "投資する", example: "The company plans to invest in new technology." },
  { word: "invoice", meaning: "請求書", example: "Please send the invoice to the accounting department." },
  { word: "launch", meaning: "立ち上げる、発売する", example: "We will launch the new product next spring." },
  { word: "maintain", meaning: "維持する、整備する", example: "We need to maintain high standards of quality." },
  { word: "manage", meaning: "管理する、経営する", example: "She manages a team of 20 people." },
  { word: "maximize", meaning: "最大化する", example: "We aim to maximize our profit margins." },
  { word: "measure", meaning: "測定する、基準", example: "We need to measure the results of the campaign." },
  { word: "negotiate", meaning: "交渉する", example: "We are negotiating the terms of the contract." },
  { word: "objective", meaning: "目標、客観的な", example: "Our main objective is to increase customer satisfaction." },
  { word: "obtain", meaning: "取得する、得る", example: "You need to obtain approval before proceeding." },
  { word: "opportunity", meaning: "機会、チャンス", example: "This merger presents a great opportunity for growth." },
  { word: "organize", meaning: "組織する、整理する", example: "Please organize the files by department." },
  { word: "outstanding", meaning: "優れた、未払いの", example: "She did an outstanding job on the presentation." },
  { word: "oversee", meaning: "監督する", example: "The director will oversee the entire project." },
  { word: "participate", meaning: "参加する", example: "All employees are encouraged to participate in the survey." },
  { word: "perform", meaning: "実行する、業績を上げる", example: "The team performed well this quarter." },
  { word: "policy", meaning: "方針、規則", example: "Please review the company's new refund policy." },
  { word: "potential", meaning: "可能性、潜在的な", example: "This market has great potential for growth." },
  { word: "priority", meaning: "優先事項", example: "Customer satisfaction is our top priority." },
  { word: "procedure", meaning: "手順、手続き", example: "Follow the standard procedure for filing complaints." },
  { word: "process", meaning: "過程、処理する", example: "The application will be processed within three days." },
  { word: "productive", meaning: "生産的な", example: "We had a very productive meeting today." },
  { word: "profit", meaning: "利益", example: "The company reported a 20% increase in profit." },
  { word: "promote", meaning: "昇進させる、宣伝する", example: "She was promoted to team leader last month." },
  { word: "propose", meaning: "提案する", example: "I would like to propose a new marketing strategy." },
  { word: "provide", meaning: "提供する", example: "We provide 24/7 customer support." },
  { word: "qualify", meaning: "資格を得る、適格である", example: "You need five years of experience to qualify for this role." },
  { word: "recognize", meaning: "認識する、表彰する", example: "The company recognizes outstanding employees each year." },
  { word: "recommend", meaning: "推薦する、お勧めする", example: "I recommend reading the full report before the meeting." },
  { word: "reduce", meaning: "減らす", example: "We are working to reduce production costs." },
  { word: "require", meaning: "必要とする", example: "This position requires excellent communication skills." },
  { word: "resolve", meaning: "解決する", example: "We resolved the issue within 24 hours." },
  { word: "resource", meaning: "資源、リソース", example: "We need more resources to complete the project on time." },
  { word: "responsible", meaning: "責任がある", example: "She is responsible for managing client accounts." },
  { word: "revenue", meaning: "収益、売上", example: "Annual revenue grew by 25% last year." },
  { word: "review", meaning: "見直す、レビュー", example: "Please review the contract before signing." },
  { word: "significant", meaning: "重要な、著しい", example: "There has been a significant improvement in sales." },
  { word: "strategy", meaning: "戦略", example: "We need a clear strategy to enter the new market." },
  { word: "submit", meaning: "提出する", example: "Please submit your report by end of day." },
  { word: "sufficient", meaning: "十分な", example: "Make sure you have sufficient funds for the project." },
  { word: "support", meaning: "支援する、サポート", example: "The IT team will support the system migration." },
  { word: "survey", meaning: "調査、アンケート", example: "We conducted a customer satisfaction survey." },
  { word: "sustainable", meaning: "持続可能な", example: "We are committed to sustainable business practices." },
  { word: "target", meaning: "目標、ターゲット", example: "We exceeded our sales target this quarter." },
  { word: "thorough", meaning: "徹底的な", example: "Please conduct a thorough review of the proposal." },
  { word: "transfer", meaning: "転送する、異動", example: "He was transferred to the Tokyo office." },
  { word: "update", meaning: "更新する、最新情報", example: "Please update the spreadsheet with the latest data." },
  { word: "utilize", meaning: "活用する", example: "We should utilize all available resources." },
  { word: "verify", meaning: "確認する、検証する", example: "Please verify that all information is correct." },
  { word: "access", meaning: "アクセスする、入手する", example: "All employees have access to the company database." },
  { word: "achievement", meaning: "達成、業績", example: "Winning the award was a great achievement for the team." },
  { word: "agreement", meaning: "合意、契約", example: "Both companies reached an agreement on the terms." },
  { word: "appeal", meaning: "訴える、魅力", example: "The new design appeals to younger customers." },
  { word: "application", meaning: "申請、応募、アプリ", example: "Your application for the loan has been approved." },
  { word: "approach", meaning: "アプローチ、取り組む", example: "We need a fresh approach to this problem." },
  { word: "approval", meaning: "承認", example: "The project needs final approval from the board." },
  { word: "arrangement", meaning: "手配、調整", example: "Please make the necessary travel arrangements." },
  { word: "article", meaning: "記事、品物", example: "The article about our company was published today." },
  { word: "association", meaning: "協会、関連", example: "She is a member of the marketing association." },
  { word: "assumption", meaning: "仮定", example: "Do not make assumptions without checking the facts." },
  { word: "atmosphere", meaning: "雰囲気、環境", example: "The office has a very positive atmosphere." },
  { word: "attachment", meaning: "添付ファイル、添付物", example: "Please find the report in the attachment." },
  { word: "attempt", meaning: "試みる、試み", example: "This is our third attempt to solve the issue." },
  { word: "attendance", meaning: "出席、参加", example: "Attendance at the training session is mandatory." },
  { word: "attention", meaning: "注意、関心", example: "Please pay attention to the safety guidelines." },
  { word: "attitude", meaning: "態度、姿勢", example: "A positive attitude is valued in our workplace." },
  { word: "audience", meaning: "聴衆、対象者", example: "The presentation was tailored to a business audience." },
  { word: "authority", meaning: "権威、当局", example: "The manager has the authority to approve expenses." },
  { word: "branch", meaning: "支店、部門", example: "We are opening a new branch in Osaka." },
  { word: "brief", meaning: "簡潔な、概要", example: "Please give me a brief summary of the report." },
  { word: "category", meaning: "カテゴリ、分類", example: "The products are organized by category." },
  { word: "certificate", meaning: "証明書、資格", example: "She received a certificate of completion." },
  { word: "challenge", meaning: "課題、挑戦", example: "The biggest challenge is reducing production costs." },
  { word: "charge", meaning: "請求する、担当", example: "Who is in charge of the marketing campaign?" },
  { word: "circumstance", meaning: "状況、事情", example: "Under these circumstances, we cannot proceed." },
  { word: "clarify", meaning: "明確にする", example: "Could you clarify what you mean by that?" },
  { word: "client", meaning: "顧客、依頼人", example: "We have over 100 corporate clients." },
  { word: "colleague", meaning: "同僚", example: "My colleague will cover for me while I am on leave." },
  { word: "commitment", meaning: "コミットメント、約束", example: "We appreciate your commitment to quality." },
  { word: "committee", meaning: "委員会", example: "The committee will review all applications." },
  { word: "communication", meaning: "コミュニケーション、連絡", example: "Clear communication is key to project success." },
  { word: "compensation", meaning: "報酬、補償", example: "The compensation package includes health insurance." },
  { word: "competent", meaning: "有能な、適切な", example: "We need a competent project manager." },
  { word: "compliance", meaning: "コンプライアンス、遵守", example: "All staff must be trained on compliance requirements." },
  { word: "concern", meaning: "懸念、関心", example: "We take customer concerns very seriously." },
  { word: "conclusion", meaning: "結論", example: "What conclusion did you reach after the analysis?" },
  { word: "condition", meaning: "条件、状態", example: "The equipment must be kept in good condition." },
  { word: "conduct", meaning: "行う、行動", example: "We will conduct a performance review next month." },
  { word: "conference", meaning: "会議、会合", example: "The annual conference will be held in Tokyo." },
  { word: "confidential", meaning: "機密の", example: "This information is strictly confidential." },
  { word: "conflict", meaning: "衝突、対立", example: "There is a scheduling conflict on that date." },
  { word: "consequence", meaning: "結果、影響", example: "Consider the consequences before making a decision." },
  { word: "consistently", meaning: "一貫して", example: "She consistently meets her targets every quarter." },
  { word: "contact", meaning: "連絡する、連絡先", example: "Please contact us if you have any questions." },
  { word: "contribution", meaning: "貢献、寄与", example: "Thank you for your contribution to the project." },
  { word: "corporation", meaning: "企業、法人", example: "The corporation has offices in 30 countries." },
  { word: "corridor", meaning: "廊下", example: "The meeting room is at the end of the corridor." },
  { word: "coverage", meaning: "保険適用範囲、報道", example: "The insurance coverage includes medical expenses." },
  { word: "criterion", meaning: "基準", example: "The selection criterion is based on experience." },
  { word: "currency", meaning: "通貨", example: "All prices are listed in the local currency." },
  { word: "decision", meaning: "決定、決断", example: "The final decision will be made by the board." },
  { word: "declaration", meaning: "宣言、申告", example: "Please fill out the customs declaration form." },
  { word: "decline", meaning: "断る、低下する", example: "Sales declined significantly last quarter." },
  { word: "dedication", meaning: "献身、熱心さ", example: "We value dedication and hard work." },
  { word: "demand", meaning: "需要、要求", example: "There is high demand for our new product." },
  { word: "departure", meaning: "出発", example: "Please arrive 30 minutes before departure." },
  { word: "description", meaning: "説明、記述", example: "The job description outlines all responsibilities." },
  { word: "designation", meaning: "指定、称号", example: "She holds the designation of senior analyst." },
  { word: "despite", meaning: "〜にもかかわらず", example: "Despite the challenges, we met the deadline." },
  { word: "distinguish", meaning: "区別する、際立たせる", example: "What distinguishes our product from competitors?" },
  { word: "division", meaning: "部門、事業部", example: "The sales division exceeded its targets." },
  { word: "domestic", meaning: "国内の、家庭の", example: "We focus on domestic markets for now." },
  { word: "duration", meaning: "期間", example: "The contract has a duration of one year." },
  { word: "effective", meaning: "効果的な", example: "This is the most effective solution." },
  { word: "efficiency", meaning: "効率", example: "We need to improve operational efficiency." },
  { word: "effort", meaning: "努力、取り組み", example: "Thank you for your efforts on this project." },
  { word: "eligible", meaning: "資格がある、適格な", example: "Employees with over two years are eligible for promotion." },
  { word: "essential", meaning: "必須の、重要な", example: "Good communication is essential for success." },
  { word: "estimate", meaning: "見積もる、推定", example: "Please provide an estimate of the total cost." },
  { word: "extension", meaning: "延長、内線", example: "Can I get an extension on the deadline?" },
  { word: "external", meaning: "外部の", example: "We hired an external consultant for the project." },
  { word: "feedback", meaning: "フィードバック、意見", example: "Please share your feedback on the proposal." },
  { word: "figure", meaning: "数字、人物", example: "The sales figures look promising." },
  { word: "final", meaning: "最終の", example: "Please submit the final report by Friday." },
  { word: "forward", meaning: "転送する、前向きな", example: "I will forward the email to the team." },
  { word: "function", meaning: "機能、役割", example: "What is the main function of this department?" },
  { word: "fund", meaning: "資金、基金", example: "We secured additional funds for the project." },
  { word: "fundamental", meaning: "基本的な、根本的な", example: "This is a fundamental change in our strategy." },
  { word: "global", meaning: "グローバルな、世界的な", example: "We are expanding our global presence." },
  { word: "goal", meaning: "目標", example: "Setting clear goals helps improve performance." },
  { word: "growth", meaning: "成長、増加", example: "We expect strong growth in the next fiscal year." },
  { word: "guideline", meaning: "ガイドライン、指針", example: "Please follow the company guidelines." },
  { word: "hire", meaning: "雇う、採用する", example: "We plan to hire 20 new employees next quarter." },
  { word: "identify", meaning: "特定する、識別する", example: "We need to identify the root cause of the issue." },
  { word: "immediate", meaning: "即座の、直接の", example: "We need an immediate response to this complaint." },
  { word: "impact", meaning: "影響、衝撃", example: "The new policy had a major impact on sales." },
  { word: "income", meaning: "収入、所得", example: "The company's income grew by 30% last year." },
  { word: "individual", meaning: "個人の、個々の", example: "Each individual is responsible for their own tasks." },
  { word: "industry", meaning: "産業、業界", example: "She has 15 years of experience in the industry." },
  { word: "inform", meaning: "知らせる", example: "Please inform the team about the schedule change." },
  { word: "installation", meaning: "設置、インストール", example: "The installation of the new equipment will take two days." },
  { word: "instruction", meaning: "指示、説明", example: "Please read the instructions carefully." },
  { word: "interact", meaning: "交流する、関わる", example: "Our staff regularly interact with customers." },
  { word: "inventory", meaning: "在庫", example: "We need to update the inventory records." },
  { word: "issue", meaning: "問題、発行", example: "We will address all issues in the next meeting." },
  { word: "leadership", meaning: "リーダーシップ", example: "Strong leadership is crucial for success." },
  { word: "location", meaning: "場所、立地", example: "The new office location is very convenient." },
  { word: "logistics", meaning: "物流、ロジスティクス", example: "We outsource our logistics to a third party." },
  { word: "mandatory", meaning: "義務的な、必須の", example: "Attendance at the training is mandatory." },
  { word: "manual", meaning: "手動の、マニュアル", example: "Please refer to the user manual for instructions." },
  { word: "margin", meaning: "利益率、余白", example: "Our profit margin has improved significantly." },
  { word: "market", meaning: "市場、マーケット", example: "We are expanding into new international markets." },
  { word: "material", meaning: "素材、資料", example: "Please prepare all training materials in advance." },
  { word: "mention", meaning: "述べる、言及する", example: "Did you mention the deadline in your email?" },
  { word: "mission", meaning: "使命、任務", example: "Our mission is to provide excellent customer service." },
  { word: "monitor", meaning: "監視する、モニター", example: "We need to monitor the project progress closely." },
  { word: "motivation", meaning: "モチベーション、動機", example: "High motivation leads to better performance." },
  { word: "mutual", meaning: "相互の", example: "We reached a mutual agreement on the terms." },
  { word: "necessary", meaning: "必要な", example: "Make all the necessary preparations for the event." },
  { word: "network", meaning: "ネットワーク、人脈", example: "Building a strong network is important in business." },
  { word: "notify", meaning: "通知する", example: "Please notify the team about the meeting change." },
  { word: "obstacle", meaning: "障害、妨げ", example: "We need to overcome this obstacle to succeed." },
  { word: "operate", meaning: "運営する、操作する", example: "The new system is easy to operate." },
  { word: "output", meaning: "産出量、成果", example: "The team's output has improved significantly." },
  { word: "outstanding", meaning: "優れた、卓越した", example: "She received an outstanding performance award." },
  { word: "partner", meaning: "パートナー、提携する", example: "We partnered with a leading tech company." },
  { word: "penalty", meaning: "罰則、ペナルティ", example: "Late payment will incur a penalty fee." },
  { word: "performance", meaning: "業績、パフォーマンス", example: "Your performance review is scheduled for next week." },
  { word: "permit", meaning: "許可する、許可証", example: "You need a permit to park in this area." },
  { word: "phase", meaning: "段階、フェーズ", example: "We are now in the second phase of the project." },
  { word: "position", meaning: "役職、立場", example: "She applied for the marketing manager position." },
  { word: "positive", meaning: "前向きな、良好な", example: "The feedback from clients has been very positive." },
  { word: "present", meaning: "発表する、提示する", example: "She will present the quarterly results tomorrow." },
  { word: "prevent", meaning: "防ぐ、妨げる", example: "We need to prevent further delays." },
  { word: "productive", meaning: "生産的な", example: "Working from home can be very productive." },
  { word: "professional", meaning: "専門家、プロの", example: "Always maintain a professional attitude at work." },
  { word: "project", meaning: "プロジェクト、見込み", example: "The project is expected to be completed in June." },
  { word: "property", meaning: "財産、不動産", example: "The company owns several properties downtown." },
  { word: "proposal", meaning: "提案、提案書", example: "Please review the proposal before the meeting." },
  { word: "prospect", meaning: "見通し、見込み客", example: "The business prospects look very promising." },
  { word: "publish", meaning: "出版する、公開する", example: "The report will be published next week." },
  { word: "purchase", meaning: "購入する、購入", example: "The company purchased new equipment last month." },
  { word: "qualification", meaning: "資格、条件", example: "What qualifications are required for this role?" },
  { word: "quarter", meaning: "四半期", example: "Profits increased significantly in the third quarter." },
  { word: "reasonable", meaning: "合理的な、妥当な", example: "The price seems very reasonable." },
  { word: "regarding", meaning: "〜に関して", example: "I am writing regarding the proposal you sent." },
  { word: "regulation", meaning: "規制、規則", example: "All companies must comply with safety regulations." },
  { word: "relationship", meaning: "関係、取引関係", example: "Building strong relationships is key to business success." },
  { word: "relevant", meaning: "関連する、適切な", example: "Please include all relevant information in your report." },
  { word: "reliable", meaning: "信頼できる", example: "We need a reliable supplier for our materials." },
  { word: "report", meaning: "報告する、報告書", example: "Please submit your monthly report by Friday." },
  { word: "representative", meaning: "代表者、担当者", example: "Our sales representative will contact you soon." },
  { word: "reputation", meaning: "評判、信頼", example: "Our company has an excellent reputation." },
  { word: "request", meaning: "依頼する、要請", example: "We received a request for a product demonstration." },
  { word: "research", meaning: "調査、研究", example: "The research team is working on a new solution." },
  { word: "result", meaning: "結果", example: "The results exceeded our expectations." },
  { word: "retain", meaning: "維持する、保持する", example: "We need to retain our best employees." },
  { word: "return", meaning: "返却する、利益", example: "We expect a strong return on this investment." },
  { word: "routine", meaning: "日課、通常の", example: "Follow your daily routine for best productivity." },
  { word: "safety", meaning: "安全", example: "Safety is our highest priority in manufacturing." },
  { word: "satisfaction", meaning: "満足度", example: "Customer satisfaction is very important to us." },
  { word: "schedule", meaning: "スケジュール、予定", example: "Please check the meeting schedule for next week." },
  { word: "sector", meaning: "部門、分野", example: "She works in the financial sector." },
  { word: "select", meaning: "選ぶ、選択する", example: "Please select the appropriate option." },
  { word: "sensitive", meaning: "敏感な、機密の", example: "Handle this sensitive information with care." },
  { word: "shipment", meaning: "出荷、荷物", example: "The shipment will arrive on Thursday." },
  { word: "skill", meaning: "スキル、技術", example: "Excellent communication skills are required." },
  { word: "solution", meaning: "解決策", example: "We found an effective solution to the problem." },
  { word: "source", meaning: "出所、情報源", example: "Please verify the source of this information." },
  { word: "specification", meaning: "仕様、明細", example: "The product specifications are in the manual." },
  { word: "staff", meaning: "スタッフ、職員", example: "The staff will be trained next week." },
  { word: "statement", meaning: "声明、明細書", example: "Please review your monthly bank statement." },
  { word: "status", meaning: "状況、状態", example: "Please update me on the project status." },
  { word: "strict", meaning: "厳格な、厳しい", example: "We have strict quality control standards." },
  { word: "success", meaning: "成功", example: "The launch was a great success." },
  { word: "suitable", meaning: "適切な、ふさわしい", example: "Is this candidate suitable for the role?" },
  { word: "supplier", meaning: "サプライヤー、供給者", example: "We are looking for a new supplier." },
  { word: "technical", meaning: "技術的な", example: "We need technical support for the installation." },
  { word: "temporary", meaning: "一時的な", example: "This is a temporary solution until the fix is ready." },
  { word: "timeline", meaning: "タイムライン、スケジュール", example: "Please share the project timeline with the team." },
  { word: "total", meaning: "合計、総計", example: "What is the total cost of the project?" },
  { word: "transaction", meaning: "取引", example: "All transactions must be recorded in the system." },
  { word: "transparent", meaning: "透明な、明確な", example: "We aim to be transparent in all business dealings." },
  { word: "trend", meaning: "トレンド、傾向", example: "The current trend shows increasing online sales." },
  { word: "unique", meaning: "独自の、ユニークな", example: "Our product has a unique feature not found elsewhere." },
  { word: "value", meaning: "価値、重視する", example: "We value customer feedback highly." },
  { word: "vendor", meaning: "販売業者、ベンダー", example: "We work with several trusted vendors." },
  { word: "voluntary", meaning: "自発的な、任意の", example: "Participation in the program is voluntary." },
  { word: "workforce", meaning: "労働力、従業員", example: "We are expanding our workforce this year." },
  { word: "workshop", meaning: "ワークショップ、研修", example: "All employees must attend the communication workshop." },
];
